import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/react";
import SignalProductPage from "./SignalPage.jsx";
import "./signal.css";

const content = {
  en: {
    nav: ["Work", "Services", "About", "Start a project"], language: "HR", languageLabel: "Read this site in Croatian",
    work: [["Custom software", "A custom application built around a small business's actual workflow.", "A lightweight web application created for a business owner who needed a better way to organise part of the company's day-to-day work.", "client"], ["Web design & development", "A modern website built for a real business.", "Strategy, structure, design and development brought together into a focused website designed to clearly communicate the company's offer and generate enquiries.", "client"], ["Web design & development", "A second custom website for a different business and audience.", "A distinct website shaped around another company's offer and customers — because one template should not define every business.", "client"], ["Business tooling", "Turning a company's offer into a sales presentation clients can understand.", "A custom PowerPoint presentation built around the company's services and sales process, giving it a professional, reusable way to present proposals.", "client"], ["Nos Astra product", "Everything holiday guests need, behind one QR code.", "Welcome Book gives apartments, villas and holiday homes a simple digital guest guide for Wi-Fi, house rules, recommendations and local information.", "product"]],
    services: [["Websites", "Websites with a job to do.", "Modern websites built around what you want visitors to do: understand your offer, make an enquiry, get in touch or buy.", "Websites →", ["Business websites", "Landing pages", "Website redesigns", "Lead-generation pages"]], ["Custom business software", "Software built around your workflow.", "Internal tools, dashboards, portals and lightweight applications for businesses that have outgrown spreadsheets, messages and disconnected tools.", "Custom software →", ["Internal dashboards", "Workflow tools", "Client portals", "Lightweight operational software"]], ["AI & automation", "AI where it actually makes sense.", "Practical AI features and workflows that reduce repeat work, process information or make existing business processes faster.", "AI solutions →", ["AI-assisted internal tools", "Document processing", "Knowledge search", "Business process automation"]]],
    steps: [["01", "Tell me what's not working", "You don't need to arrive with a technical specification. Explain the repetitive task or frustrating workflow."], ["02", "Find the smallest useful solution", "The answer might be a website, application, automation or something much simpler."], ["03", "Build and iterate", "You see the work early rather than disappearing into a months-long development process."], ["04", "Put it to work", "The goal is not to ship software. The goal is something useful enough that the business actually uses it."]],
    hero: ["SOFTWARE & AI STUDIO", "Digital solutions for a growing business.", "We build modern websites, custom applications and AI automations that help small businesses work more simply, quickly and efficiently.", "Start a project", "", ""],
    proof: ["Proof, not promises", "Built for real businesses.", "Nos Astra builds practical digital tools for companies that need something better than another generic piece of software.", "Websites delivered", "Custom software in production", "Digital products used by paying customers", "AI and business workshops delivered"],
    home: ["Selected work", "Things we’ve built for real businesses.", "See all work →", "Services", "What can we build?", "Explore services →", "How we work", "Start with the problem, not the technology."],
    founder: ["The person behind Nos Astra", "Hi, I’m Tamara.", "I’m an AI engineer and software developer with a previous career in scientific research and teaching.", "I started Nos Astra to build practical software for businesses that don’t need a giant development team — they need someone who can understand the problem, figure out what should be built and make it work.", "When you work with Nos Astra, you work directly with me from the first conversation through to the finished product.", "More about me →"],
    contact: ["Start a project", "Have something in your business that should work better?", "It doesn’t need to be a fully formed app idea. Tell us what’s slow, repetitive, awkward or frustrating and we’ll figure out whether software can help.", "No technical brief required.", "Your name", "Email address", "Company", "optional", "What are you trying to solve?", "Tell us what you're doing today, what isn't working and what you'd like to happen instead.", "Sending…", "Send enquiry", "Thanks — we’ll be in touch shortly.", "Something went wrong. Please try again in a moment."],
    pages: { work: ["Work", "Websites, custom tools and digital products built for real businesses."], services: ["What can we build together?", "Nos Astra builds small, focused digital solutions for businesses. You don’t need to know which technology you need. Start with the problem."], about: ["Nos Astra", "Small software. Useful software."] },
    unusual: ["The unusual projects", "Doesn’t fit neatly into one of those categories?", "Good. Some of the most interesting projects start with: “Every week I have to do this stupid thing manually and I hate it.”", "Tell me the stupid thing →"],
    studio: ["An independent software and AI studio in Croatia.", "We build websites, custom tools and practical AI solutions, primarily for small businesses.", "The goal isn’t to make software bigger than it needs to be. It’s to understand what isn’t working and build the smallest useful thing that fixes it.", "Why Nos Astra exists", "The interesting projects usually start with a complaint.", "I don’t particularly care about building software simply because software can be built. I care about the moment when someone says: “We currently do this manually,” or “This part of the business drives me crazy.” That’s usually the beginning of something worth building."],
    footer: ["Software & AI studio", "Croatia · Working remotely", "Studio", "Elsewhere", "Privacy Policy"], title: "Nos Astra: Software & AI Studio", description: "Start is a launch package for new businesses. Nos Astra also builds practical software and AI solutions.",
    start: { eyebrow: "For new businesses", title: "A professional start, made easier.", intro: "Start your business with the essentials in place — and a professional presence online.", priceLabel: "Start package", price: "€250", priceNote: "One-time price for the services listed below.", includedLabel: "The foundations for your business", items: [["Professional website", "A clear place to present your services and contact details."], ["Basic SEO", "Basic SEO setup and a connection to Google Search Console so your website is ready for Google Search."], ["Business card design", "A print-ready design that matches your business identity."], ["Web app for preparing quotes", "Create, save and edit client quotes in one place."], ["Business email setup", "You buy and pay for the domain separately; I connect it to your business email. Google Workspace (Gmail) is paid. Zoho Mail has a free plan if available and suitable for your needs."]], ctaEyebrow: "Interested in the Start package?", ctaTitle: "Send an enquiry.", ctaCopy: "You don’t need a long brief. Send an enquiry and I’ll reply personally.", name: "Your name", company: "Business name", email: "Email address", phone: "Phone number", contactHint: "Please enter an email address or phone number so I can reply.", message: "Anything else you’d like to add?", messageHint: "Optional — tell me a little about your new business.", submit: "Send enquiry", sending: "Sending…", sent: "Thank you! Your enquiry has been sent. I’ll be in touch soon.", error: "Your enquiry could not be sent. Please try again or email start@nosastra.co.", emailLabel: "Email me", phoneLabel: "Call me", heroCta: "Ask about Start" }
  },
  hr: {
    nav: ["Radovi", "Usluge", "O nama", "Započnite projekt"], language: "EN", languageLabel: "Read this site in English",
    work: [["Prilagođeni softver", "Aplikacija izrađena prema stvarnom načinu rada malog poduzeća.", "Jednostavna web aplikacija izrađena za vlasnika poduzeća kojem je trebao bolji način za organizaciju dijela svakodnevnog poslovanja.", "client"], ["Web dizajn i razvoj", "Moderna web-stranica za stvarno poduzeće.", "Strategija, struktura, dizajn i razvoj objedinjeni u fokusiranu web-stranicu koja jasno predstavlja ponudu tvrtke i potiče upite.", "client"], ["Web dizajn i razvoj", "Druga prilagođena web-stranica za drukčije poduzeće i publiku.", "Zasebna web-stranica oblikovana prema ponudi i kupcima druge tvrtke — jer jedan predložak ne bi trebao određivati svako poduzeće.", "client"], ["Poslovni alati", "Pretvaranje ponude tvrtke u prodajnu prezentaciju koju klijenti razumiju.", "Prilagođena PowerPoint prezentacija zasnovana na uslugama i prodajnom procesu tvrtke, za profesionalan i višekratno upotrebljiv način predstavljanja ponuda.", "client"], ["Nos Astra proizvod", "Sve što gostima na odmoru treba, iza jednog QR koda.", "Welcome Book apartmanima, vilama i kućama za odmor pruža jednostavan digitalni vodič za goste s Wi-Fi podacima, kućnim redom, preporukama i lokalnim informacijama.", "product"]],
    services: [["Web-stranice", "Web-stranice sa svrhom.", "Moderne web-stranice oblikovane prema tome što želite da posjetitelji naprave: razumiju vašu ponudu, pošalju upit, jave se ili kupe.", "Web-stranice →", ["Web-stranice za poduzeća", "Odredišne stranice", "Redizajn web-stranice", "Stranice za prikupljanje upita"]], ["Prilagođeni poslovni softver", "Softver prilagođen vašem načinu rada.", "Interni alati, nadzorne ploče, portali i jednostavne aplikacije za poduzeća koja su prerasla proračunske tablice, poruke i nepovezane alate.", "Prilagođeni softver →", ["Interne nadzorne ploče", "Alati za radne procese", "Portali za klijente", "Jednostavan operativni softver"]], ["AI i automatizacija", "AI tamo gdje stvarno ima smisla.", "Praktične AI funkcionalnosti i radni procesi koji smanjuju ponavljajući posao, obrađuju informacije ili ubrzavaju postojeće poslovne procese.", "AI rješenja →", ["Interni alati uz AI", "Obrada dokumenata", "Pretraživanje znanja", "Automatizacija poslovnih procesa"]]],
    steps: [["01", "Recite mi što ne funkcionira", "Ne trebate doći s tehničkom specifikacijom. Opišite zadatak koji se ponavlja ili proces koji vas frustrira."], ["02", "Pronađimo najmanje korisno rješenje", "Rješenje može biti web-stranica, aplikacija, automatizacija ili nešto puno jednostavnije."], ["03", "Izrada i dorada", "Rad vidite rano, umjesto da projekt nestane u višemjesečnom procesu razvoja."], ["04", "Primijenite ga u poslu", "Cilj nije samo isporučiti softver. Cilj je stvoriti nešto dovoljno korisno da ga poduzeće zaista koristi."]],
    hero: ["SOFTWARE & AI STUDIO", "Digitalna rješenja za poslovanje koje raste.", "Izrađujemo moderne web stranice, prilagođene aplikacije i AI automatizacije koje malim poduzećima pomažu raditi jednostavnije, brže i učinkovitije.", "Započnite projekt", "Pogledajte radove →", ""],
    proof: ["Dokazi, ne obećanja", "Izrađeno za stvarna poduzeća.", "Nos Astra izrađuje praktične digitalne alate za tvrtke kojima treba nešto bolje od još jednog generičkog softvera.", "Isporučene web-stranice", "Prilagođeni softver u produkciji", "Digitalni proizvodi koje koriste kupci koji plaćaju", "Održane AI i poslovne radionice"],
    home: ["Odabrani radovi", "Ono što smo izradili za stvarna poduzeća.", "Pogledajte sve radove →", "Usluge", "Što možemo izraditi?", "Istražite usluge →", "Kako radimo", "Počnite od problema, ne od tehnologije."],
    founder: ["Osoba iza Nos Astre", "Bok, ja sam Tamara.", "AI sam inženjerka i softverska razvojna inženjerka, a prije toga sam radila u znanstvenom istraživanju i obrazovanju.", "Nos Astru pokrenula sam kako bih izrađivala praktičan softver za poduzeća kojima ne treba golemi razvojni tim — treba im netko tko može razumjeti problem, odlučiti što treba izraditi i pobrinuti se da funkcionira.", "Kada radite s Nos Astrom, od prvog razgovora do gotovog proizvoda radite izravno sa mnom.", "Više o meni →"],
    contact: ["Započnite projekt", "Imate li u poslovanju nešto što bi trebalo raditi bolje?", "Ne mora biti potpuno oblikovana ideja za aplikaciju. Recite nam što je sporo, ponavljajuće, nezgrapno ili frustrirajuće pa ćemo zajedno vidjeti može li softver pomoći.", "Tehnički brief nije potreban.", "Vaše ime", "Email adresa", "Tvrtka", "neobavezno", "Što pokušavate riješiti?", "Recite nam kako to danas radite, što ne funkcionira i što biste željeli da se dogodi.", "Slanje…", "Pošaljite upit", "Hvala — javit ćemo Vam se uskoro.", "Nešto nije uspjelo. Pokušajte ponovno za trenutak."],
    pages: { work: ["Radovi", "Web-stranice, prilagođeni alati i digitalni proizvodi izrađeni za stvarna poduzeća."], services: ["Što možemo izraditi zajedno?", "Nos Astra izrađuje mala, fokusirana digitalna rješenja za poduzeća. Ne trebate znati koja vam tehnologija treba. Počnite od problema."], about: ["Nos Astra", "Mali softver. Koristan softver."] },
    unusual: ["Neobični projekti", "Ne uklapa se uredno ni u jednu od tih kategorija?", "Odlično. Neki od najzanimljivijih projekata počinju ovako: „Svaki tjedan ovo moram ručno raditi i ide mi na živce.”", "Recite mi što vas živcira →"],
    studio: ["Neovisni softverski i AI studio u Hrvatskoj.", "Izrađujemo web-stranice, prilagođene alate i praktična AI rješenja, prvenstveno za mala poduzeća.", "Cilj nije napraviti softver većim nego što treba biti. Cilj je razumjeti što ne funkcionira i izraditi najmanju korisnu stvar koja to rješava.", "Zašto Nos Astra postoji", "Zanimljivi projekti najčešće počinju pritužbom.", "Ne zanima me posebno izrada softvera samo zato što se softver može izraditi. Zanima me trenutak kada netko kaže: „Ovo trenutačno radimo ručno” ili „Ovaj dio poslovanja me izluđuje.” To je obično početak nečega što vrijedi izraditi."],
    footer: ["Softverski i AI studio", "Hrvatska · Suradnja na daljinu", "Studio", "Ostalo", "Pravila privatnosti"], title: "Nos Astra — Start i praktična digitalna rješenja", description: "Upoznajte Start, paket za nova poduzeća. Nos Astra izrađuje i praktičan softver i AI rješenja.",
    start: { eyebrow: "Za nova poduzeća", title: "Za profesionalan i lak početak.", intro: "Pokrenite poslovanje s temeljnim stvarima na mjestu — i profesionalnim nastupom online.", priceLabel: "Start paket", price: "250 €", priceNote: "Jednokratna cijena za navedene usluge.", includedLabel: "Temelji za vaše poslovanje", items: [["Profesionalna web stranica", "Jasno mjesto za predstavljanje vaših usluga i kontaktnih podataka."], ["Osnovni SEO", "Osnovne SEO postavke i povezivanje s Google Search Console kako bi web stranica bila spremna za Google pretraživanje."], ["Dizajn poslovne kartice", "Dizajn spreman za tisak, usklađen s vizualnim identitetom tvrtke."], ["Web aplikacija za pripremu ponuda", "Pripremajte, spremajte i uređujte ponude za klijente na jednom mjestu."], ["Postavljanje poslovnog e-maila", "Domenu kupujete i plaćate zasebno, a ja je povezujem s poslovnim e-mailom. Google Workspace (Gmail) se plaća; Zoho Mail ima besplatan plan ako je dostupan i odgovara vašim potrebama."]], emailNote: "Domenu kupujete i posjedujete vi. Registraciju domene i eventualnu plaćenu Google Workspace pretplatu naplaćuju pružatelji usluge; dostupnost besplatnog Zoho Mail plana ovisi o regiji i potrebama.", ctaEyebrow: "Zanima vas Start paket?", ctaTitle: "Pošaljite upit.", ctaCopy: "Ne treba vam dugačak opis. Pošaljite upit i osobno ću vam se javiti.", name: "Vaše ime", company: "Naziv tvrtke", email: "Email adresa", phone: "Broj telefona", contactHint: "Obavezno upišite email adresu ili broj telefona kako bismo vam mogli odgovoriti.", message: "Želite li još nešto dodati?", messageHint: "Neobavezno — recite mi ukratko nešto o svom novom poslovanju.", submit: "Pošaljite poruku", sending: "Slanje…", sent: "Hvala! Upit je poslan. Javit ću vam se uskoro.", error: "Slanje nije uspjelo. Pokušajte ponovno ili pišite na start@nosastra.co.", emailLabel: "Pošaljite mi e-mail", phoneLabel: "Nazovite me", heroCta: "Zanima me Start paket" }
  }
};

function Brand() { return <><svg className="brand-mark" viewBox="0 0 64 64" aria-hidden="true"><path className="mark-body" d="M 32 2 Q 35.99 15.99 39.64 21.48 L 60.53 22.73 Q 48.46 30.85 44.36 36.02 L 49.63 56.27 Q 38.18 47.3 32 45 L 14.37 56.27 Q 19.36 42.61 19.64 36.02 L 3.47 22.73 Q 18.01 23.26 24.36 21.48 Z" /><path className="mark-facet" d="M 32 2 Q 35.99 15.99 39.64 21.48 L 32 32 Z M 60.53 22.73 Q 48.46 30.85 44.36 36.02 L 32 32 Z M 49.63 56.27 Q 38.18 47.3 32 45 L 32 32 Z M 14.37 56.27 Q 19.36 42.61 19.64 36.02 L 32 32 Z M 3.47 22.73 Q 18.01 23.26 24.36 21.48 L 32 32 Z" /></svg><span className="brand-name">Nos <span>Astra</span></span></>; }
const localPath = (path, hr) => path === "/start" ? (hr ? "/start" : "/en/start") : hr ? `/hr${path === "/" ? "" : path}` : path;

function LanguageFlag({ hr }) {
  return <img className={`language-flag ${hr ? "flag-gb" : "flag-hr"}`} src={hr ? "/flags/gb.svg" : "/flags/hr.svg"} width="34" height={hr ? "20" : "17"} alt="" />;
}

function Header({ t, hr, path }) { return <header className="site-header"><div className="shell nav"><a className="brand" href={localPath("/", hr)} aria-label="Nos Astra home"><Brand /></a><nav className="nav-links" aria-label={hr ? "Glavna navigacija" : "Main navigation"}><a href={localPath("/", hr)} aria-current={path === "/" ? "page" : undefined}>{hr ? "Početna" : "Home"}</a><a href={localPath("/start", hr)} aria-current={path === "/start" ? "page" : undefined}>Start</a><a href={localPath("/signal", hr)} aria-current={path === "/signal" ? "page" : undefined}>Signal</a><a className="language-link" href={localPath(path, !hr)} aria-label={t.languageLabel} title={hr ? "English" : "Hrvatski"}><LanguageFlag hr={hr} /></a><a className="contact-link hero-cta" href={`${localPath("/", hr)}#contact`}><span className="hero-cta-face">{t.nav[3]}</span></a></nav></div></header>; }
function ContactForm({ t, hr }) { const [state, setState] = useState("idle"); async function submit(e) { e.preventDefault(); const form = e.currentTarget; setState("sending"); try { const response = await fetch("https://formspree.io/f/xpqvovvv", { method: "POST", body: new FormData(form), headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(); form.reset(); setState("sent"); } catch { setState("error"); } } return <form className="contact-form" onSubmit={submit}><input type="hidden" name="language" value={hr ? "Croatian" : "English"} /><div className="form-field"><label htmlFor="name">{t.contact[4]} <span aria-hidden="true">*</span></label><input id="name" name="name" autoComplete="name" required /></div><div className="form-field"><label htmlFor="email">{t.contact[5]} <span aria-hidden="true">*</span></label><input id="email" name="email" type="email" autoComplete="email" required /></div><div className="form-field form-field-wide"><label htmlFor="company">{t.contact[6]}</label><input id="company" name="company" autoComplete="organization" /></div><div className="form-field form-field-wide"><label htmlFor="message">{t.contact[8]} <span aria-hidden="true">*</span></label><textarea id="message" name="message" required /></div><button className="button" type="submit" disabled={state === "sending"}>{state === "sending" ? t.contact[10] : t.contact[11]}</button><p className={`form-status${state === "error" ? " is-error" : ""}`} aria-live="polite">{state === "sent" ? t.contact[12] : state === "error" ? t.contact[13] : ""}</p></form>; }
function ProjectCard({ project, t, hr, large = false }) { const [label, title, copy, kind] = project; const welcome = kind === "product"; return <article className={`project-card ${large ? "project-card-large " : ""}${welcome ? "is-product" : ""}`}><div className="project-visual"><span>{welcome ? "Welcome Book" : hr ? "Pregled projekta" : "Project preview"}</span></div><div className="project-content"><p className="kicker">{label}</p><h3>{title}</h3><p>{copy}</p>{welcome ? <a className="text-link" href="https://welcomebook.eu" target="_blank" rel="noreferrer">{hr ? "Istražite Welcome Book →" : "Explore Welcome Book →"}</a> : null}</div></article>; }
function ServiceCard({ service, t, hr, full = false }) { const [name, title, copy, cta, items] = service; return <article className={`service-card${full ? " service-card-full" : ""}`}><p className="kicker">{name}</p><h2>{title}</h2><p>{copy}</p>{full && <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul>}<a className="text-link" href={`${localPath("/", hr)}#contact`}>{full ? (hr ? (name === t.services[0][0] ? "Razgovarajmo o web-stranici →" : name === t.services[1][0] ? "Recite mi što ne funkcionira →" : "Istražite AI ideju →") : (name === "Websites" ? "Talk about a website →" : name === "Custom business software" ? "Tell me what's not working →" : "Explore an AI idea →")) : cta}</a></article>; }
function Proof({ t }) { return <section className="proof-section"><div className="shell"><div className="section-intro"><p className="kicker">{t.proof[0]}</p><h2>{t.proof[1]}</h2><p className="section-copy">{t.proof[2]}</p></div><div className="proof-list">{t.proof.slice(3).map((item) => <span key={item}>{item}</span>)}</div></div></section>; }
function CroatianHomeMiddle() {
  const services = [
    ["01", "Web stranice i web aplikacije", "Moderne web stranice i web aplikacije koje ne služe samo za predstavljanje, već pomažu Vašem poslovanju."],
    ["02", "Prilagođeni poslovni alati", "Jednostavni interni alati za ponude, klijente, projekte, evidencije i svakodnevne procese."],
    ["03", "AI i automatizacija", "Povezivanje alata i automatizacija ponavljajućih zadataka kako biste uštedjeli vrijeme i smanjili ručni rad."],
    ["04", "Radionice i edukacije", "Praktične AI radionice za male timove, prilagođene Vašem poslovanju. Pomažemo Vam koristiti AI, automatizaciju i digitalne alate u svakodnevnom radu."]
  ];
  return <>
    <section className="studio-services"><div className="shell"><div className="section-intro"><p className="kicker">Što možemo izraditi za Vas</p><h2>Rješenja prilagođena načinu na koji Vaše poslovanje stvarno funkcionira.</h2><p className="section-copy">Od edukacije do izvedbe, pomažemo malim poduzećima razumjeti, uvesti i koristiti tehnologiju koja im stvarno koristi.</p></div><div className="studio-service-grid">{services.map(([number, title, copy]) => <article className="studio-service" key={title}><span className="studio-service-number">{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <Products hr />
  </>;
}
function FinalCta({ t, hr }) { return <section id="contact" className="final-cta"><div className="shell contact"><div className="contact-panel"><div><p className="kicker">{t.contact[0]}</p><h2>{t.contact[1]}</h2></div><ContactForm t={t} hr={hr} /></div></div></section>; }
function StartPackageForm({ t, hr }) { const [state, setState] = useState("idle"); async function submit(e) { e.preventDefault(); const form = e.currentTarget; const email = form.elements.email; const phone = form.elements.phone; email.setCustomValidity(""); if (!email.value.trim() && !phone.value.trim()) { email.setCustomValidity(t.start.contactHint); email.reportValidity(); email.addEventListener("input", () => email.setCustomValidity(""), { once: true }); phone.addEventListener("input", () => email.setCustomValidity(""), { once: true }); return; } setState("sending"); try { const response = await fetch("https://formspree.io/f/xpqvovvv", { method: "POST", body: new FormData(form), headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(); form.reset(); setState("sent"); } catch { setState("error"); } } return <form className="contact-form start-form" onSubmit={submit}><input type="hidden" name="language" value={hr ? "Croatian" : "English"} /><input type="hidden" name="enquiry_type" value="Start package" /><div className="form-field"><label htmlFor="start-name">{t.start.name} <span aria-hidden="true">*</span></label><input id="start-name" name="name" autoComplete="name" required /></div><div className="form-field"><label htmlFor="start-company">{t.start.company} <span aria-hidden="true">*</span></label><input id="start-company" name="company" autoComplete="organization" required /></div><div className="form-field"><label htmlFor="start-email">{t.start.email}</label><input id="start-email" name="email" type="email" autoComplete="email" /></div><div className="form-field"><label htmlFor="start-phone">{t.start.phone}</label><input id="start-phone" name="phone" type="tel" autoComplete="tel" /></div><div className="form-field form-field-wide"><label htmlFor="start-message">{t.start.message}</label><textarea id="start-message" name="message" placeholder={t.start.messageHint} /></div><button className="button" type="submit" disabled={state === "sending"}>{state === "sending" ? t.start.sending : t.start.submit}</button><p className={`form-status${state === "error" ? " is-error" : ""}`} aria-live="polite">{state === "sent" ? t.start.sent : state === "error" ? t.start.error : ""}</p></form>; }
function StartPackagePage({ t, hr }) {
  const s = t.start;
  const cardLabel = hr ? "Dizajn poslovne kartice" : "Business card design";
  const items = [...s.items.filter(([name]) => name !== cardLabel), ...s.items.filter(([name]) => name === cardLabel)];
  return <main className="start-page">
    <section className="start-hero"><div className="shell start-hero-grid">
      <div><p className="kicker">{s.eyebrow}</p><h1>{s.title}</h1><p className="start-intro">{s.intro}</p><a className="hero-cta" href="#start-contact"><span className="hero-cta-face">{s.heroCta}</span></a></div>
      <aside className="start-price-card"><p className="kicker">{s.priceLabel}</p><p className="start-price">{s.price}</p><p>{s.priceNote}</p>
        <ul>{items.map(([name]) => <li key={name}>{hr && name === cardLabel ? "Dizajn vizitke" : name}</li>)}</ul>
      </aside>
    </div></section>
    <section className="start-included"><div className="shell"><div className="section-intro"><p className="kicker">{s.priceLabel}</p><h2>{s.includedLabel}</h2></div><div className="start-item-grid">{items.map(([name, copy], index) => <article className="start-item" key={name}><span className="start-item-number">0{index + 1}</span><h3>{hr && name === cardLabel ? "Dizajn vizitke" : name}</h3><p>{copy}</p></article>)}</div></div></section>
    <section id="start-contact" className="start-contact"><div className="shell contact"><div className="contact-panel"><div className="start-contact-copy"><div><p className="kicker">{s.ctaEyebrow}</p><h2>{s.ctaTitle}</h2></div><div className="start-direct-contact">
      <a href="mailto:start@nosastra.co"><span className="start-contact-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m4 7 8 6 8-6" /></svg></span><span><small>E-mail</small><strong>start@nosastra.co</strong></span></a>
      <a href="tel:+385992142439"><span className="start-contact-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M6.7 3.5h3l1.4 4.2-2 1.7a15.3 15.3 0 0 0 5.5 5.5l1.7-2 4.2 1.4v3a2.5 2.5 0 0 1-2.8 2.5A17.5 17.5 0 0 1 4.2 6.3 2.5 2.5 0 0 1 6.7 3.5Z" /></svg></span><span><small>Telefon</small><strong>+385 99 214 2439</strong></span></a>
    </div></div><StartPackageForm t={t} hr={hr} /></div></div></section>
  </main>;
}
function Products({ hr }) {
  return <section id="products" className="products-section"><div className="shell">
    <div className="products-heading">
      <p className="kicker">{hr ? "Proizvodi Nos Astre" : "Nos Astra products"}</p>
      <h2>{hr ? "Temelji za profesionalan početak poslovanja." : "The essentials for a professional business launch."}</h2>
      <p>{hr ? "Start Vam pomaže postaviti temelje za novo poslovanje." : "Start helps you put the essentials in place for your new business."}</p>
    </div>
    <div className="product-grid product-grid-single">
      <article className="product-card product-card-start">
        <div className="product-card-top"><span>01 / Start</span><span>{hr ? "Paket za početak" : "Launch package"}</span></div>
        <h3>Start</h3>
        <p className="product-card-lead">{hr ? "Profesionalan početak za novo poduzeće." : "A professional start for a new business."}</p>
        <p>{hr ? "Web stranica, osnovni SEO, dizajn vizitke, poslovni e-mail i aplikacija za ponude u jednom paketu." : "A website, basic SEO, business card design, business email and a quote app in one package."}</p>
        <a href={localPath("/start", hr)}>{hr ? "Istražite Start" : "Explore Start"}<span aria-hidden="true">↗</span></a>
      </article>
    </div>
  </div></section>;
}
function Home({ t, hr }) { return <main id="top"><section className="hero"><div className="hero-content"><div><p className="kicker">{t.hero[0]}</p><h1>{t.hero[1]}</h1><p className="hero-copy">{t.hero[2]}</p><div className="hero-actions"><a className="hero-cta" href="#contact"><span className="hero-cta-face">{t.hero[3]}</span></a></div><p className="hero-note">{t.hero[5]}</p></div></div><div className="hero-image"><picture><source media="(max-width: 800px)" srcSet="/nos-astra-hero-mobile-v1.webp" type="image/webp" /><source srcSet="/nos-astra-hero-desktop-v5.webp" type="image/webp" /><img src="/nos-astra-hero-desktop-v5.png" width="1672" height="941" fetchPriority="high" alt={hr ? "Apstraktna zvjezdana skulptura u maslinastim i grafitnim tonovima" : "Abstract olive and graphite star sculpture"} /></picture></div></section><div id="studio-services">{hr ? <CroatianHomeMiddle /> : <EnglishHomeMiddle />}</div><HowWeWork hr={hr} /><FinalCta t={t} hr={hr} /></main>; }
function HowWeWork({ hr }) {
  const steps = hr ? [
    ["1", "Razgovor", "Upoznajemo Vaše poslovanje, postojeći način rada i ono što Vam stvara najviše problema."],
    ["2", "Prijedlog", "Predlažemo najjednostavnije rješenje, bez izrade nečega što Vam zapravo nije potrebno."],
    ["3", "Izrada", "Gradimo, testiramo i prilagođavamo rješenje zajedno s Vama."],
    ["4", "Pokretanje", "Dobivate jasno objašnjenje kako koristiti rješenje i što je sljedeći korak."]
  ] : [
    ["1", "Conversation", "We get to know your business, how you currently work and what causes you the most problems."],
    ["2", "Proposal", "We suggest the simplest solution, without building anything you don’t actually need."],
    ["3", "Development", "We build, test and refine the solution together with you."],
    ["4", "Launch", "You receive a clear explanation of how to use the solution and what the next step is."]
  ];
  return <section className="process-section"><div className="shell"><div className="section-intro"><h2>{hr ? "Kako radimo" : "How we work"}</h2></div><div className="steps">{steps.map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>;
}
function EnglishHomeMiddle() {
  const services = [
    ["01", "Websites and web applications", "Modern websites and web applications that do more than introduce your business. They help it work better."],
    ["02", "Custom business tools", "Simple internal tools for quotes, clients, projects, records and everyday processes."],
    ["03", "AI and automation", "Connecting tools and automating repetitive tasks to save time and reduce manual work."],
    ["04", "Workshops and training", "Practical AI workshops for small teams, tailored to your business. We help you use AI, automation and digital tools in your everyday work."]
  ];
  return <>
    <section className="studio-services"><div className="shell"><div className="section-intro"><p className="kicker">What we can build for you</p><h2>Solutions tailored to the way your business actually works.</h2><p className="section-copy">From understanding to implementation, we help small businesses understand, adopt and use technology that genuinely helps them.</p></div><div className="studio-service-grid">{services.map(([number, title, copy]) => <article className="studio-service" key={title}><span className="studio-service-number">{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <Products hr={false} />
  </>;
}
function Footer({ t, hr, path }) { const contactEmail = path === "/start" ? "start@nosastra.co" : path === "/signal" ? "signal@nosastra.co" : "hello@nosastra.co"; return <footer className="site-footer"><div className="shell"><div className="footer-main"><div className="footer-brand"><a className="brand" href={localPath("/", hr)} aria-label="Nos Astra home"><Brand /></a><p className="footer-tagline">Software &amp; AI Studio</p></div><nav className="footer-nav" aria-label={hr ? "Navigacija u podnožju" : "Footer navigation"}>{path !== "/start" && path !== "/signal" && <a href={localPath("/start", hr)}>Start ↗</a>}<a href={`mailto:${contactEmail}`}>{contactEmail} ↗</a></nav><div className="footer-legal"><p>© {new Date().getFullYear()} Nos Astra.</p><div className="footer-legal-links"><a href={hr ? "/hr/privacy.html" : "/privacy.html"}>{t.footer[4]}</a><details className="business-details"><summary>{hr ? "Podaci o poslovanju" : "Legal information"}</summary><dl><dt>{hr ? "Registrirani naziv" : "Registered business name"}</dt><dd>Nos Astra, obrt za računalno programiranje i savjetovanje, vl. Tamara Martinović, Njivice, Cvjetni trg 3</dd><dt>{hr ? "Vlasnica" : "Owner"}</dt><dd>Tamara Martinović</dd><dt>{hr ? "Sjedište" : "Registered address"}</dt><dd>Cvjetni trg 3, Njivice, {hr ? "Hrvatska" : "Croatia"}</dd><dt>OIB</dt><dd>23795034700</dd><dt>{hr ? "Matični broj obrta" : "Craft registration number"}</dt><dd>99335433</dd><dt>{hr ? "Registar" : "Register"}</dt><dd>{hr ? "Obrtni registar Republike Hrvatske" : "Croatian Craft Register"}</dd><dt>{hr ? "Datum upisa" : "Registration date"}</dt><dd>15.07.2026.</dd><dt>Email</dt><dd><a href="mailto:hello@nosastra.co">hello@nosastra.co</a></dd></dl></details></div></div></div></div></footer>; }
function App() { const rawPath = window.location.pathname.replace(/\/$/, "") || "/"; const isCroatianStart = rawPath === "/start" || rawPath === "/hr/start"; const isEnglishStart = rawPath === "/en/start"; const hr = isCroatianStart || rawPath === "/hr" || rawPath.startsWith("/hr/"); const requestedPath = isCroatianStart || isEnglishStart ? "/start" : (hr ? rawPath.replace(/^\/hr/, "") : rawPath) || "/"; const path = ["/work", "/services", "/about"].includes(requestedPath) ? "/" : requestedPath; const t = content[hr ? "hr" : "en"]; useEffect(() => { const url = `https://www.nosastra.co${localPath(path, hr)}`; const title = path === "/start" ? t.start.priceLabel : path === "/signal" ? "Signal" : t.title; const description = path === "/start" ? t.start.intro : path === "/signal" ? (hr ? "Razumijte AI vidljivost svoje tvrtke." : "Understand your business's AI visibility.") : t.description; document.documentElement.lang = hr ? "hr" : "en"; document.documentElement.dir = "ltr"; document.title = path === "/" ? t.title : `${title} — Nos Astra`; document.querySelector('meta[name="description"]')?.setAttribute("content", description); document.querySelector('meta[property="og:description"]')?.setAttribute("content", description); document.querySelector('meta[property="og:title"]')?.setAttribute("content", document.title); document.querySelector('meta[property="og:locale"]')?.setAttribute("content", hr ? "hr_HR" : "en_GB"); document.querySelector('link[rel="canonical"]')?.setAttribute("href", url); document.querySelector('meta[property="og:url"]')?.setAttribute("content", url); }, [hr, path, t]); useEffect(() => { const header = document.querySelector("#root .site-header"); const onScroll = () => header?.classList.toggle("is-scrolled", window.scrollY > 24); addEventListener("scroll", onScroll, { passive: true }); onScroll(); return () => removeEventListener("scroll", onScroll); }, []); const Page = path === "/start" ? StartPackagePage : path === "/signal" ? SignalProductPage : Home; return <>{path !== "/signal" && <Header t={t} hr={hr} path={path} />}{path === "/signal" ? <Page hr={hr} /> : <Page t={t} hr={hr} />}<Footer t={t} hr={hr} path={path} /><Analytics /><SpeedInsights /></>; }
const alternateRoute = window.location.pathname.replace(/\/$/, "") || "/";
const alternatePaths = ["/signal", "/hr/signal"].includes(alternateRoute)
  ? ["/signal", "/hr/signal"]
  : ["/start", "/en/start", "/hr/start"].includes(alternateRoute)
  ? ["/en/start", "/start"]
  : ["/", "/hr"];
for (const [language, route] of [["en", alternatePaths[0]], ["hr", alternatePaths[1]], ["x-default", alternatePaths[0]]]) {
  document.querySelector(`link[rel="alternate"][hreflang="${language}"]`)?.setAttribute("href", `https://www.nosastra.co${route}`);
}
if (window.location.pathname.replace(/\/$/, "") === "/hr/start") {
  window.location.replace(`/start${window.location.search}${window.location.hash}`);
} else {
  createRoot(document.getElementById("root")).render(<App />);
}
