import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/react";

const content = {
  en: {
    nav: ["Work", "Services", "About", "Start a project"], language: "HR", languageLabel: "Read this site in Croatian",
    work: [["Custom software", "A custom application built around a small business's actual workflow.", "A lightweight web application created for a business owner who needed a better way to organise part of the company's day-to-day work.", "client"], ["Web design & development", "A modern website built for a real business.", "Strategy, structure, design and development brought together into a focused website designed to clearly communicate the company's offer and generate enquiries.", "client"], ["Web design & development", "A second custom website for a different business and audience.", "A distinct website shaped around another company's offer and customers — because one template should not define every business.", "client"], ["Business tooling", "Turning a company's offer into a sales presentation clients can understand.", "A custom PowerPoint presentation built around the company's services and sales process, giving it a professional, reusable way to present proposals.", "client"], ["Nos Astra product", "Everything holiday guests need, behind one QR code.", "Welcome Book gives apartments, villas and holiday homes a simple digital guest guide for Wi-Fi, house rules, recommendations and local information.", "product"]],
    services: [["Websites", "Websites with a job to do.", "Modern websites built around what you want visitors to do: understand your offer, make an enquiry, get in touch or buy.", "Websites →", ["Business websites", "Landing pages", "Website redesigns", "Lead-generation pages"]], ["Custom business software", "Software built around your workflow.", "Internal tools, dashboards, portals and lightweight applications for businesses that have outgrown spreadsheets, messages and disconnected tools.", "Custom software →", ["Internal dashboards", "Workflow tools", "Client portals", "Lightweight operational software"]], ["AI & automation", "AI where it actually makes sense.", "Practical AI features and workflows that reduce repeat work, process information or make existing business processes faster.", "AI solutions →", ["AI-assisted internal tools", "Document processing", "Knowledge search", "Business process automation"]]],
    steps: [["01", "Tell me what's not working", "You don't need to arrive with a technical specification. Explain the repetitive task or frustrating workflow."], ["02", "Find the smallest useful solution", "The answer might be a website, application, automation or something much simpler."], ["03", "Build and iterate", "You see the work early rather than disappearing into a months-long development process."], ["04", "Put it to work", "The goal is not to ship software. The goal is something useful enough that the business actually uses it."]],
    hero: ["Software & AI studio · Croatia", "Software that makes small businesses run better.", "Websites, custom tools and AI-powered solutions built around the way your business actually works.", "Start a project", "See the work →", "Built in Croatia. Working with businesses remotely."],
    proof: ["Proof, not promises", "Built for real businesses.", "Nos Astra builds practical digital tools for companies that need something better than another generic piece of software.", "Websites delivered", "Custom software in production", "Digital products used by paying customers", "AI and business workshops delivered"],
    home: ["Selected work", "Things we’ve built for real businesses.", "See all work →", "Services", "What can we build?", "Explore services →", "How we work", "Start with the problem, not the technology."],
    founder: ["The person behind Nos Astra", "Hi, I’m Tamara.", "I’m an AI engineer and software developer with a previous career in scientific research and teaching.", "I started Nos Astra to build practical software for businesses that don’t need a giant development team — they need someone who can understand the problem, figure out what should be built and make it work.", "When you work with Nos Astra, you work directly with me from the first conversation through to the finished product.", "More about me →"],
    contact: ["Start a project", "Have something in your business that should work better?", "It doesn’t need to be a fully formed app idea. Tell me what’s slow, repetitive, awkward or frustrating and we’ll figure out whether software can help.", "No technical brief required.", "Your name", "Email address", "Company", "optional", "What are you trying to solve?", "Tell me what you're doing today, what isn't working and what you'd like to happen instead.", "Sending…", "Send project enquiry", "Thanks — I’ll be in touch shortly.", "Something went wrong. Please try again in a moment."],
    pages: { work: ["Work", "Websites, custom tools and digital products built for real businesses."], services: ["What can we build together?", "Nos Astra builds small, focused digital solutions for businesses. You don’t need to know which technology you need. Start with the problem."], about: ["Nos Astra", "Small software. Useful software."] },
    unusual: ["The unusual projects", "Doesn’t fit neatly into one of those categories?", "Good. Some of the most interesting projects start with: “Every week I have to do this stupid thing manually and I hate it.”", "Tell me the stupid thing →"],
    studio: ["An independent software and AI studio in Croatia.", "We build websites, custom tools and practical AI solutions, primarily for small businesses.", "The goal isn’t to make software bigger than it needs to be. It’s to understand what isn’t working and build the smallest useful thing that fixes it.", "Why Nos Astra exists", "The interesting projects usually start with a complaint.", "I don’t particularly care about building software simply because software can be built. I care about the moment when someone says: “We currently do this manually,” or “This part of the business drives me crazy.” That’s usually the beginning of something worth building."],
    footer: ["Software & AI studio", "Croatia · Working remotely", "Studio", "Elsewhere", "Privacy Policy"], title: "Nos Astra: Software & AI Studio", description: "Nos Astra builds websites, custom business tools and practical AI solutions for small businesses. Based in Croatia, working remotely.",
    start: { eyebrow: "For new construction businesses", title: "A professional start, without the usual setup scramble.", intro: "Your first clients shouldn’t have to piece together who you are from a phone number and a half-finished Facebook page. Get the essentials in place, then get back to the work you’re good at.", priceLabel: "Start package", price: "€250", priceNote: "A one-time setup price for the items below.", includedLabel: "A tidy foundation for your business", items: [["A professional website", "A clear, mobile-friendly home for your services and contact details."], ["Business card design", "A print-ready design that matches your new business identity."], ["Offer preparation web app", "Prepare, save and edit customer offers in one place."], ["Business email setup", "Choose Google Workspace with Gmail or Zoho Mail, connected to your domain."], ["Invoice design", "A reusable invoice design that fits your brand; your accountant or invoicing software remains the source for compliant invoices."]], mobileEyebrow: "For the team on site", mobileTitle: "Know what’s happening at the job site.", mobileCopy: "A mobile app for your team to report completed work, missing materials and what needs attention, while the details are still fresh.", mobilePrice: "€10 / month", mobileNote: "Available to Start package clients. Your monthly price stays at €10 for as long as your subscription is active.", emailNote: "You buy and own the domain. Domain registration and any paid Google Workspace subscription are billed by their providers; Zoho Mail may offer a free plan depending on availability and needs.", ctaEyebrow: "Want to get the basics sorted?", ctaTitle: "Tell me a little about your new business.", ctaCopy: "No long brief needed. Send an enquiry and I’ll get back to you personally.", name: "Your name", company: "Company name", email: "Email address", phone: "Phone number", contactHint: "Please add an email address or phone number so I can reply.", message: "Anything you’d like me to know?", messageHint: "Optional — for example, what kind of construction work you do.", submit: "I’m interested in the Start package", sending: "Sending…", sent: "Thanks! Your enquiry is on its way. I’ll be in touch soon.", error: "That didn’t go through. Please try again or email hello@nosastra.co.", emailLabel: "Email me", phoneLabel: "Call me", heroCta: "Talk about the package" }
  },
  hr: {
    nav: ["Radovi", "Usluge", "O nama", "Započnite projekt"], language: "EN", languageLabel: "Read this site in English",
    work: [["Prilagođeni softver", "Aplikacija izrađena prema stvarnom načinu rada malog poduzeća.", "Jednostavna web aplikacija izrađena za vlasnika poduzeća kojem je trebao bolji način za organizaciju dijela svakodnevnog poslovanja.", "client"], ["Web dizajn i razvoj", "Moderna web-stranica za stvarno poduzeće.", "Strategija, struktura, dizajn i razvoj objedinjeni u fokusiranu web-stranicu koja jasno predstavlja ponudu tvrtke i potiče upite.", "client"], ["Web dizajn i razvoj", "Druga prilagođena web-stranica za drukčije poduzeće i publiku.", "Zasebna web-stranica oblikovana prema ponudi i kupcima druge tvrtke — jer jedan predložak ne bi trebao određivati svako poduzeće.", "client"], ["Poslovni alati", "Pretvaranje ponude tvrtke u prodajnu prezentaciju koju klijenti razumiju.", "Prilagođena PowerPoint prezentacija zasnovana na uslugama i prodajnom procesu tvrtke, za profesionalan i višekratno upotrebljiv način predstavljanja ponuda.", "client"], ["Nos Astra proizvod", "Sve što gostima na odmoru treba, iza jednog QR koda.", "Welcome Book apartmanima, vilama i kućama za odmor pruža jednostavan digitalni vodič za goste s Wi-Fi podacima, kućnim redom, preporukama i lokalnim informacijama.", "product"]],
    services: [["Web-stranice", "Web-stranice sa svrhom.", "Moderne web-stranice oblikovane prema tome što želite da posjetitelji naprave: razumiju vašu ponudu, pošalju upit, jave se ili kupe.", "Web-stranice →", ["Web-stranice za poduzeća", "Odredišne stranice", "Redizajn web-stranice", "Stranice za prikupljanje upita"]], ["Prilagođeni poslovni softver", "Softver prilagođen vašem načinu rada.", "Interni alati, nadzorne ploče, portali i jednostavne aplikacije za poduzeća koja su prerasla proračunske tablice, poruke i nepovezane alate.", "Prilagođeni softver →", ["Interne nadzorne ploče", "Alati za radne procese", "Portali za klijente", "Jednostavan operativni softver"]], ["AI i automatizacija", "AI tamo gdje stvarno ima smisla.", "Praktične AI funkcionalnosti i radni procesi koji smanjuju ponavljajući posao, obrađuju informacije ili ubrzavaju postojeće poslovne procese.", "AI rješenja →", ["Interni alati uz AI", "Obrada dokumenata", "Pretraživanje znanja", "Automatizacija poslovnih procesa"]]],
    steps: [["01", "Recite mi što ne funkcionira", "Ne trebate doći s tehničkom specifikacijom. Opišite zadatak koji se ponavlja ili proces koji vas frustrira."], ["02", "Pronađimo najmanje korisno rješenje", "Rješenje može biti web-stranica, aplikacija, automatizacija ili nešto puno jednostavnije."], ["03", "Izrada i dorada", "Rad vidite rano, umjesto da projekt nestane u višemjesečnom procesu razvoja."], ["04", "Primijenite ga u poslu", "Cilj nije samo isporučiti softver. Cilj je stvoriti nešto dovoljno korisno da ga poduzeće zaista koristi."]],
    hero: ["Softverski i AI studio · Hrvatska", "Softver koji malim poduzećima olakšava poslovanje.", "Web-stranice, prilagođeni alati i AI rješenja izrađena prema načinu na koji vaše poduzeće stvarno radi.", "Započnite projekt", "Pogledajte radove →", "Izrađeno u Hrvatskoj. Suradnja na daljinu."],
    proof: ["Dokazi, ne obećanja", "Izrađeno za stvarna poduzeća.", "Nos Astra izrađuje praktične digitalne alate za tvrtke kojima treba nešto bolje od još jednog generičkog softvera.", "Isporučene web-stranice", "Prilagođeni softver u produkciji", "Digitalni proizvodi koje koriste kupci koji plaćaju", "Održane AI i poslovne radionice"],
    home: ["Odabrani radovi", "Ono što smo izradili za stvarna poduzeća.", "Pogledajte sve radove →", "Usluge", "Što možemo izraditi?", "Istražite usluge →", "Kako radimo", "Počnite od problema, ne od tehnologije."],
    founder: ["Osoba iza Nos Astre", "Bok, ja sam Tamara.", "AI sam inženjerka i softverska razvojna inženjerka, a prije toga sam radila u znanstvenom istraživanju i obrazovanju.", "Nos Astru pokrenula sam kako bih izrađivala praktičan softver za poduzeća kojima ne treba golemi razvojni tim — treba im netko tko može razumjeti problem, odlučiti što treba izraditi i pobrinuti se da funkcionira.", "Kada radite s Nos Astrom, od prvog razgovora do gotovog proizvoda radite izravno sa mnom.", "Više o meni →"],
    contact: ["Započnite projekt", "Imate li u poslovanju nešto što bi trebalo raditi bolje?", "Ne mora biti potpuno oblikovana ideja za aplikaciju. Recite mi što je sporo, ponavljajuće, nezgrapno ili frustrirajuće pa ćemo zajedno vidjeti može li softver pomoći.", "Tehnički brief nije potreban.", "Vaše ime", "E-adresa", "Tvrtka", "neobavezno", "Što pokušavate riješiti?", "Recite mi kako to danas radite, što ne funkcionira i što biste željeli da se dogodi.", "Slanje…", "Pošaljite upit za projekt", "Hvala — javit ću vam se uskoro.", "Nešto nije uspjelo. Pokušajte ponovno za trenutak."],
    pages: { work: ["Radovi", "Web-stranice, prilagođeni alati i digitalni proizvodi izrađeni za stvarna poduzeća."], services: ["Što možemo izraditi zajedno?", "Nos Astra izrađuje mala, fokusirana digitalna rješenja za poduzeća. Ne trebate znati koja vam tehnologija treba. Počnite od problema."], about: ["Nos Astra", "Mali softver. Koristan softver."] },
    unusual: ["Neobični projekti", "Ne uklapa se uredno ni u jednu od tih kategorija?", "Odlično. Neki od najzanimljivijih projekata počinju ovako: „Svaki tjedan ovo moram ručno raditi i ide mi na živce.”", "Recite mi što vas živcira →"],
    studio: ["Neovisni softverski i AI studio u Hrvatskoj.", "Izrađujemo web-stranice, prilagođene alate i praktična AI rješenja, prvenstveno za mala poduzeća.", "Cilj nije napraviti softver većim nego što treba biti. Cilj je razumjeti što ne funkcionira i izraditi najmanju korisnu stvar koja to rješava.", "Zašto Nos Astra postoji", "Zanimljivi projekti najčešće počinju pritužbom.", "Ne zanima me posebno izrada softvera samo zato što se softver može izraditi. Zanima me trenutak kada netko kaže: „Ovo trenutačno radimo ručno” ili „Ovaj dio poslovanja me izluđuje.” To je obično početak nečega što vrijedi izraditi."],
    footer: ["Softverski i AI studio", "Hrvatska · Suradnja na daljinu", "Studio", "Ostalo", "Pravila privatnosti"], title: "Nos Astra — Web-stranice, prilagođeni softver i AI rješenja", description: "Nos Astra izrađuje web-stranice, prilagođene poslovne alate i praktična AI rješenja za mala poduzeća. Iz Hrvatske, za klijente na daljinu.",
    start: { eyebrow: "Za nove obrte i firme", title: "Za profesionalan i lak početak.", intro: "Vi gradite na terenu, a ja ću vam pomoći da posao izgleda jednako dobro i online.", priceLabel: "Start paket", price: "250 €", priceNote: "Jednokratna cijena za navedene usluge.", includedLabel: "Temelji za vaše poslovanje", items: [["Profesionalna web stranica", "Jasno mjesto za predstavljanje vaših usluga i kontaktnih podataka."], ["Osnovni SEO", "Osnovne SEO postavke i povezivanje s Google Search Console kako bi web stranica bila spremna za Google pretraživanje."], ["Dizajn poslovne kartice", "Dizajn spreman za tisak, usklađen s vizualnim identitetom tvrtke."], ["Web aplikacija za pripremu ponuda", "Pripremajte, spremajte i uređujte ponude za klijente na jednom mjestu."], ["Postavljanje poslovnog e-maila", "Domenu kupujete i plaćate zasebno, a ja je povezujem s poslovnim e-mailom. Google Workspace (Gmail) se plaća; Zoho Mail ima besplatan plan ako je dostupan i odgovara vašim potrebama."], ["Dizajn računa", "Predložak računa za višekratnu upotrebu, usklađen s vašim brendom."]], mobileEyebrow: "Za radnike na gradilištu", mobileTitle: "Znajte što se događa na gradilištu.", mobileCopy: "Mobilna aplikacija u kojoj radnici mogu prijaviti obavljene radove, materijal koji nedostaje i ono na što treba obratiti pozornost — dok su detalji još svježi.", mobilePrice: "10 € mjesečno", mobileNote: "Dostupno klijentima Start paketa. Cijena ostaje 10 € mjesečno dok je vaša pretplata aktivna.", emailNote: "Domenu kupujete i posjedujete vi. Registraciju domene i eventualnu plaćenu Google Workspace pretplatu naplaćuju pružatelji usluge; dostupnost besplatnog Zoho Mail plana ovisi o regiji i potrebama.", ctaEyebrow: "Zanima vas Start paket?", ctaTitle: "Pošaljite upit.", ctaCopy: "Ne treba vam dugačak opis. Pošaljite upit i osobno ću vam se javiti.", name: "Vaše ime", company: "Naziv tvrtke", email: "E-adresa", phone: "Broj telefona", contactHint: "Upišite e-adresu ili broj telefona kako bih vam mogla odgovoriti.", message: "Želite li još nešto dodati?", messageHint: "Neobavezno — primjerice, kojom se vrstom građevinskih radova bavite.", submit: "Pošaljite poruku", sending: "Slanje…", sent: "Hvala! Upit je poslan. Javit ću vam se uskoro.", error: "Slanje nije uspjelo. Pokušajte ponovno ili pišite na hello@nosastra.co.", emailLabel: "Pošaljite mi e-mail", phoneLabel: "Nazovite me", heroCta: "Zanima me Start paket" }
  }
};

function Brand() { return <><svg className="brand-mark" viewBox="0 0 64 64" aria-hidden="true"><path className="mark-body" d="M 32 2 Q 35.99 15.99 39.64 21.48 L 60.53 22.73 Q 48.46 30.85 44.36 36.02 L 49.63 56.27 Q 38.18 47.3 32 45 L 14.37 56.27 Q 19.36 42.61 19.64 36.02 L 3.47 22.73 Q 18.01 23.26 24.36 21.48 Z" /><path className="mark-facet" d="M 32 2 Q 35.99 15.99 39.64 21.48 L 32 32 Z M 60.53 22.73 Q 48.46 30.85 44.36 36.02 L 32 32 Z M 49.63 56.27 Q 38.18 47.3 32 45 L 32 32 Z M 14.37 56.27 Q 19.36 42.61 19.64 36.02 L 32 32 Z M 3.47 22.73 Q 18.01 23.26 24.36 21.48 L 32 32 Z" /></svg><span className="brand-name">Nos <span>Astra</span></span></>; }
const localPath = (path, hr) => path === "/start" ? "/start" : hr ? `/hr${path === "/" ? "" : path}` : path;

function Header({ t, hr, path }) { return <header className="site-header"><div className="shell nav"><a className="brand" href={localPath("/", hr)} aria-label="Nos Astra home"><Brand /></a><nav className="nav-links" aria-label="Main navigation"><a href={localPath("/work", hr)}>{t.nav[0]}</a><a href={localPath("/services", hr)}>{t.nav[1]}</a><a href={localPath("/about", hr)}>{t.nav[2]}</a>{path !== "/start" && <a className="language-link" href={localPath(path, !hr)} aria-label={t.languageLabel}>{t.language}</a>}<a className="contact-link" href={`${localPath("/", hr)}#contact`}>{t.nav[3]} →</a></nav></div></header>; }
function ContactForm({ t, hr }) { const [state, setState] = useState("idle"); async function submit(e) { e.preventDefault(); const form = e.currentTarget; setState("sending"); try { const response = await fetch("https://formspree.io/f/xpqvovvv", { method: "POST", body: new FormData(form), headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(); form.reset(); setState("sent"); } catch { setState("error"); } } return <form className="contact-form" onSubmit={submit}><input type="hidden" name="language" value={hr ? "Croatian" : "English"} /><div className="form-field"><label htmlFor="name">{t.contact[4]}</label><input id="name" name="name" autoComplete="name" required /></div><div className="form-field"><label htmlFor="email">{t.contact[5]}</label><input id="email" name="email" type="email" autoComplete="email" required /></div><div className="form-field form-field-wide"><label htmlFor="company">{t.contact[6]} <span>{t.contact[7]}</span></label><input id="company" name="company" autoComplete="organization" /></div><div className="form-field form-field-wide"><label htmlFor="message">{t.contact[8]}</label><textarea id="message" name="message" placeholder={t.contact[9]} required /></div><button className="button" type="submit" disabled={state === "sending"}>{state === "sending" ? t.contact[10] : t.contact[11]}</button><p className={`form-status${state === "error" ? " is-error" : ""}`} aria-live="polite">{state === "sent" ? t.contact[12] : state === "error" ? t.contact[13] : ""}</p></form>; }
function ProjectCard({ project, t, hr, large = false }) { const [label, title, copy, kind] = project; const welcome = kind === "product"; return <article className={`project-card ${large ? "project-card-large " : ""}${welcome ? "is-product" : ""}`}><div className="project-visual"><span>{welcome ? "Welcome Book" : hr ? "Pregled projekta" : "Project preview"}</span></div><div className="project-content"><p className="kicker">{label}</p><h3>{title}</h3><p>{copy}</p>{welcome ? <a className="text-link" href="https://welcomebook.eu" target="_blank" rel="noreferrer">{hr ? "Istražite Welcome Book →" : "Explore Welcome Book →"}</a> : <a className="text-link" href={localPath("/work", hr)}>{hr ? "Pogledajte projekt →" : "View project →"}</a>}</div></article>; }
function ServiceCard({ service, t, hr, full = false }) { const [name, title, copy, cta, items] = service; return <article className={`service-card${full ? " service-card-full" : ""}`}><p className="kicker">{name}</p><h2>{title}</h2><p>{copy}</p>{full && <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul>}<a className="text-link" href={`${localPath("/", hr)}#contact`}>{full ? (hr ? (name === t.services[0][0] ? "Razgovarajmo o web-stranici →" : name === t.services[1][0] ? "Recite mi što ne funkcionira →" : "Istražite AI ideju →") : (name === "Websites" ? "Talk about a website →" : name === "Custom business software" ? "Tell me what's not working →" : "Explore an AI idea →")) : cta}</a></article>; }
function Proof({ t }) { return <section className="proof-section"><div className="shell"><div className="section-intro"><p className="kicker">{t.proof[0]}</p><h2>{t.proof[1]}</h2><p className="section-copy">{t.proof[2]}</p></div><div className="proof-list">{t.proof.slice(3).map((item) => <span key={item}>{item}</span>)}</div></div></section>; }
function Founder({ t, hr }) { return <section className="founder-section"><div className="shell founder-layout"><div className="portrait"><picture><source srcSet="/tamara-martinovic.webp" type="image/webp" /><img src="/tamara-martinovic.jpg" width="1254" height="1254" loading="lazy" decoding="async" alt={hr ? "Tamara Martinović, osnivačica Nos Astre" : "Tamara Martinovic, founder of Nos Astra"} /></picture></div><div className="founder-copy"><p className="kicker">{t.founder[0]}</p><h2>{t.founder[1]}</h2><p>{t.founder[2]}</p><p>{t.founder[3]}</p><p>{t.founder[4]}</p><a className="text-link" href="https://tamara.rocks" target="_blank" rel="noreferrer">{t.founder[5]}</a></div></div></section>; }
function FinalCta({ t, hr }) { return <section id="contact" className="final-cta"><div className="shell contact"><div className="contact-panel"><div><p className="kicker">{t.contact[0]}</p><h2>{t.contact[1]}</h2><p className="contact-note">{t.contact[2]}</p><p className="contact-note"><strong>{t.contact[3]}</strong></p></div><ContactForm t={t} hr={hr} /></div></div></section>; }
function StartPackageForm({ t, hr }) { const [state, setState] = useState("idle"); async function submit(e) { e.preventDefault(); const form = e.currentTarget; const email = form.elements.email; const phone = form.elements.phone; email.setCustomValidity(""); if (!email.value.trim() && !phone.value.trim()) { email.setCustomValidity(t.start.contactHint); email.reportValidity(); email.addEventListener("input", () => email.setCustomValidity(""), { once: true }); phone.addEventListener("input", () => email.setCustomValidity(""), { once: true }); return; } setState("sending"); try { const response = await fetch("https://formspree.io/f/xpqvovvv", { method: "POST", body: new FormData(form), headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(); form.reset(); setState("sent"); } catch { setState("error"); } } return <form className="contact-form start-form" onSubmit={submit}><input type="hidden" name="language" value={hr ? "Croatian" : "English"} /><input type="hidden" name="enquiry_type" value="Start package" /><div className="form-field"><label htmlFor="start-name">{t.start.name}</label><input id="start-name" name="name" autoComplete="name" required /></div><div className="form-field"><label htmlFor="start-company">{t.start.company}</label><input id="start-company" name="company" autoComplete="organization" /></div><div className="form-field"><label htmlFor="start-email">{t.start.email}</label><input id="start-email" name="email" type="email" autoComplete="email" /></div><div className="form-field"><label htmlFor="start-phone">{t.start.phone}</label><input id="start-phone" name="phone" type="tel" autoComplete="tel" /></div><p className="start-form-hint">{t.start.contactHint}</p><div className="form-field form-field-wide"><label htmlFor="start-message">{t.start.message}</label><textarea id="start-message" name="message" placeholder={t.start.messageHint} /></div><button className="button" type="submit" disabled={state === "sending"}>{state === "sending" ? t.start.sending : t.start.submit}</button><p className={`form-status${state === "error" ? " is-error" : ""}`} aria-live="polite">{state === "sent" ? t.start.sent : state === "error" ? t.start.error : ""}</p></form>; }
function StartMobileCroatian() {
  const features = [
    ["Dnevni radovi", "Evidencija obavljenih radova za svako gradilište."],
    ["Fotografije i video", "Radnici uz prijavu mogu priložiti fotografije i videozapise."],
    ["Materijal i narudžbe", "Pregled materijala koji nedostaje ili ga treba naručiti."],
    ["Dodatni radovi i zastoji", "Evidencija dodatnih radova, problema i zastoja na gradilištu."],
    ["Pregled i podsjetnici", "Kalendar prijava i podsjetnici za radnike."],
  ];
  const weekdays = ["Pon", "Uto", "Sri", "Čet", "Pet", "Sub", "Ned"];
  const [view, setView] = useState("entry");
  const [adminPage, setAdminPage] = useState("calendar");
  const [entry, setEntry] = useState(null);
  const [notifications, setNotifications] = useState([{ id: "sample-reminder", message: "Ne zaboravite upisati što ste danas radili.", hour: "10", minute: "00", days: [...weekdays] }]);
  const [newReminderDays, setNewReminderDays] = useState([...weekdays]);
  const [saveNotice, setSaveNotice] = useState(false);
  const [selectedSite, setSelectedSite] = useState("Gradilište A");
  const [notificationsEnabled, setNotificationsEnabled] = useState(false);
  const [reportFlags, setReportFlags] = useState({ material: true, extra: false, problems: false, order: false });
  const today = new Date();
  const [selectedDay, setSelectedDay] = useState(today.getDate());
  const year = today.getFullYear();
  const month = today.getMonth();
  const firstWeekday = (new Date(year, month, 1).getDay() + 6) % 7;
  const daysInMonth = new Date(year, month + 1, 0).getDate();
  const calendarDays = [...Array(firstWeekday).fill(null), ...Array.from({ length: daysInMonth }, (_, index) => index + 1)];
  useEffect(() => () => {
    if (entry?.mediaUrl) URL.revokeObjectURL(entry.mediaUrl);
  }, [entry]);

  function saveEntry(event) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = new FormData(form);
    const file = form.elements.media.files[0];
    setEntry({
      day: new Date().getDate(),
      site: selectedSite,
      description: String(data.get("description") || "").trim(),
      flags: { ...reportFlags },
      notes: { material: String(data.get("materialNote") || "").trim(), extra: String(data.get("extraNote") || "").trim(), problems: String(data.get("problemNote") || "").trim(), order: String(data.get("orderNote") || "").trim() },
      mediaName: file?.name || "",
      mediaType: file?.type || "",
      mediaUrl: file ? URL.createObjectURL(file) : "",
    });
    setSelectedDay(new Date().getDate());
    setSaveNotice(true);
  }

  function saveNotification(event) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    setNotifications((items) => [{ id: crypto.randomUUID(), message: String(data.get("notificationMessage") || "").trim(), hour: String(data.get("hour") || "16"), minute: String(data.get("minute") || "00"), days: [...newReminderDays] }, ...items]);
    event.currentTarget.reset();
    setNewReminderDays([...weekdays]);
  }

  function updateReminder(id, changes) {
    setNotifications((items) => items.map((item) => item.id === id ? { ...item, ...changes } : item));
  }

  return <section id="start-mobile" className="start-mobile"><div className="shell">
    <div className="start-mobile-overview"><p className="kicker">Mobilna aplikacija za gradilište</p><h2>Sve s gradilišta. Na jednom mjestu.</h2><p>Radnici putem aplikacije unose obavljene radove, materijal koji nedostaje i probleme na gradilištu. Vi sve pratite na jednom mjestu.</p></div>
    <div className="start-mobile-showcase">
      <div className="start-mobile-features"><h3>Što aplikacija prati?</h3><ul>{features.map(([title, copy]) => <li key={title}><strong>{title}</strong><span>{copy}</span></li>)}</ul></div>
      <figure className="start-mobile-figure"><div className="start-mobile-demo" aria-label="Interaktivni prikaz mobilne aplikacije">
        <div className="start-demo-topline"><span>DEMO APLIKACIJA</span></div>
        <div className="start-demo-header"><strong className="start-demo-title">{view === "entry" ? "Dnevnik radova" : "Admin"}</strong>{view === "entry" ? <button className="start-demo-admin-button" type="button" onClick={() => setView("admin")}>Admin</button> : <button className="start-demo-back-button" type="button" onClick={() => setView("entry")}>Natrag na aplikaciju</button>}</div>
        {view === "entry" ? <form className="start-demo-body start-demo-form" onSubmit={saveEntry}>
          {saveNotice && <p className="start-demo-confirmation" role="status"><span aria-hidden="true">✓</span> Vaša prijava je spremljena.</p>}
          <button className="start-demo-notifications" type="button" aria-pressed={notificationsEnabled} onClick={() => setNotificationsEnabled((enabled) => !enabled)}>{notificationsEnabled ? "Obavijesti uključene" : "Uključi obavijesti"}</button>
          <div className="start-demo-sites" role="group" aria-label="Odaberite gradilište">{["Gradilište A", "Gradilište B"].map((site) => <button type="button" key={site} className={selectedSite === site ? "is-selected" : ""} aria-pressed={selectedSite === site} onClick={() => setSelectedSite(site)}>{site}</button>)}</div>
          <div className="start-demo-card start-demo-work-card">
            <label className="start-demo-field">Slike i video<input name="media" type="file" accept="image/*,video/*" /></label>
            <label className="start-demo-field">Što ste danas radili?<textarea name="description" rows="3" placeholder="" required /></label>
          </div>
          <div className="start-demo-card start-demo-switches">{[["material", "Je li sav materijal na gradilištu?", "materialNote", "Koji materijal nedostaje?"], ["extra", "Ima li dodatnih radova za naplatu?", "extraNote", "Opišite dodatne radove za naplatu"], ["problems", "Problemi ili zastoji?", "problemNote", "Opišite problem ili zastoj"], ["order", "Treba li nešto naručiti?", "orderNote", "Što treba naručiti?"]].map(([key, label, fieldName, placeholder]) => <div className="start-demo-switch-item" key={key}><label className="start-demo-switch-row"><span>{label}</span><input type="checkbox" checked={reportFlags[key]} onChange={(event) => setReportFlags((flags) => ({ ...flags, [key]: event.target.checked }))} /><i aria-hidden="true" /></label>{(key === "material" ? !reportFlags[key] : reportFlags[key]) && <input className="start-demo-followup" type="text" name={fieldName} placeholder={placeholder} required aria-label={placeholder} />}</div>)}</div>
          <button className="start-demo-save" type="submit">Spremi</button>
        </form> : <div className="start-demo-body start-demo-admin">
          <div className="start-demo-admin-nav" role="tablist" aria-label="Administratorski pregled">
            <button type="button" role="tab" aria-selected={adminPage === "calendar"} className={adminPage === "calendar" ? "is-active" : ""} onClick={() => setAdminPage("calendar")}>Unosi</button>
            <button type="button" role="tab" aria-selected={adminPage === "notifications"} className={adminPage === "notifications" ? "is-active" : ""} onClick={() => setAdminPage("notifications")}>Postavke</button>
          </div>
          {adminPage === "calendar" ? <>
            <div className="start-demo-calendar"><strong>{today.toLocaleDateString("hr-HR", { month: "long", year: "numeric" })}</strong><div className="start-demo-days">{weekdays.map((day) => <span key={day}>{day}</span>)}{calendarDays.map((day, index) => day === null ? <span key={"empty-" + index} /> : <button type="button" key={day} className={(selectedDay === day ? "is-selected " : "") + (entry?.day === day ? "has-entry" : "")} onClick={() => setSelectedDay(day)} aria-label={day + ". " + (month + 1) + ". " + year + (entry?.day === day ? " — spremljena prijava" : "")} aria-pressed={selectedDay === day}>{day}{entry?.day === day && <i aria-hidden="true" />}</button>)}</div></div>
            <div className="start-demo-entry"><strong>{selectedDay}. {today.toLocaleDateString("hr-HR", { month: "long" })}</strong>{entry?.day === selectedDay ? <><p><b>{entry.site}</b> · {entry.description}</p>{entry.flags && <p>{Object.entries(entry.flags).map(([key, active]) => ({ material: active ? "Sav materijal je na gradilištu" : entry.notes?.material, extra: active ? "Dodatni radovi za naplatu" : "", problems: active ? "Problemi ili zastoji" : "", order: active ? "Potrebno je naručiti materijal" : "" }[key])).filter(Boolean).join(" · ")}</p>}{entry.notes && <div className="start-demo-notes">{[["extra", "Dodatni radovi"], ["problems", "Problem ili zastoj"], ["order", "Za naručiti"], ["material", "Nedostaje materijal"]].filter(([key]) => entry.notes[key]).map(([key, label]) => <p key={key}><b>{label}:</b> {entry.notes[key]}</p>)}</div>}{entry.mediaUrl && (entry.mediaType.startsWith("image/") ? <img src={entry.mediaUrl} alt={"Priložena fotografija: " + entry.mediaName} /> : <video src={entry.mediaUrl} controls preload="metadata" aria-label={"Priloženi video: " + entry.mediaName} />)}{entry.mediaName && <small>{entry.mediaName}</small>}</> : <p>Nema prijava za odabrani dan.</p>}</div>
          </> : <div className="start-demo-settings-page">
            <h3>Postavke</h3>
            <p>Dodajte koliko god želite podsjetnika za radnike — svaki sa svojom porukom, vremenom i danima.</p>
            <span className="start-demo-section-label">Nova obavijest</span>
            <form className="start-demo-notification-form" onSubmit={saveNotification}>
              <label>Poruka obavijesti<textarea name="notificationMessage" rows="2" placeholder="Npr. Ne zaboravite upisati što ste danas radili." required /></label>
              <label>Vrijeme<span className="start-demo-time-fields"><select name="hour" defaultValue="16" aria-label="Sat">{Array.from({ length: 24 }, (_, hour) => String(hour).padStart(2, "0")).map((hour) => <option key={hour}>{hour}</option>)}</select><span>:</span><select name="minute" defaultValue="00" aria-label="Minute">{Array.from({ length: 60 }, (_, minute) => String(minute).padStart(2, "0")).map((minute) => <option key={minute}>{minute}</option>)}</select></span></label>
              <fieldset className="start-demo-weekday-picker"><legend>Dani u tjednu</legend><div>{weekdays.map((day) => <button type="button" key={day} className={newReminderDays.includes(day) ? "is-active" : ""} aria-pressed={newReminderDays.includes(day)} onClick={() => setNewReminderDays((days) => days.includes(day) ? days.filter((item) => item !== day) : weekdays.filter((item) => days.includes(item) || item === day))}>{day}</button>)}</div></fieldset>
              <button className="start-demo-add-notification" type="submit">Dodaj obavijest</button>
            </form>
            <span className="start-demo-section-label">Postojeće obavijesti</span>
            <div className="start-demo-notification-list">{notifications.map((item) => <article key={item.id}>
              <label>Poruka obavijesti<textarea rows="2" value={item.message} onChange={(event) => updateReminder(item.id, { message: event.target.value })} /></label>
              <label>Vrijeme<span className="start-demo-time-fields"><select value={item.hour} aria-label="Sat" onChange={(event) => updateReminder(item.id, { hour: event.target.value })}>{Array.from({ length: 24 }, (_, hour) => String(hour).padStart(2, "0")).map((hour) => <option key={hour}>{hour}</option>)}</select><span>:</span><select value={item.minute} aria-label="Minute" onChange={(event) => updateReminder(item.id, { minute: event.target.value })}>{Array.from({ length: 60 }, (_, minute) => String(minute).padStart(2, "0")).map((minute) => <option key={minute}>{minute}</option>)}</select></span></label>
              <fieldset className="start-demo-weekday-picker"><legend>Dani u tjednu</legend><div>{weekdays.map((day) => <button type="button" key={day} className={item.days.includes(day) ? "is-active" : ""} aria-pressed={item.days.includes(day)} onClick={() => updateReminder(item.id, { days: item.days.includes(day) ? item.days.filter((value) => value !== day) : weekdays.filter((value) => item.days.includes(value) || value === day) })}>{day}</button>)}</div></fieldset>
              <button className="start-demo-remove-notification" type="button" onClick={() => setNotifications((items) => items.filter((reminder) => reminder.id !== item.id))}>Ukloni obavijest</button>
            </article>)}</div>
          </div>}
        </div>}
      </div></figure>
    </div>
    <div className="start-mobile-plans"><div className="start-mobile-plans-copy"><span className="kicker">Posebna cijena</span><p>Kupnjom Start paketa trajno ostvarujete povlaštenu cijenu za aplikaciju. Pretplata se plaća zasebno.</p></div><div className="start-mobile-plan"><span>Mjesečno</span><strong>10 €</strong><small>svaki mjesec</small></div><div className="start-mobile-plan"><span>Godišnje</span><strong>100 €</strong><small>20 € manje godišnje</small></div></div>
  </div></section>;
}
function StartPackagePage({ t, hr }) {
  const s = t.start;
  const cardLabel = hr ? "Dizajn poslovne kartice" : "Business card design";
  const items = [...s.items.filter(([name]) => name !== cardLabel), ...s.items.filter(([name]) => name === cardLabel)];
  return <main className="start-page">
    <section className="start-hero"><div className="shell start-hero-grid">
      <div><p className="kicker">{s.eyebrow}</p><h1>{s.title}</h1><p className="start-intro">{s.intro}</p><a className="hero-cta" href="#start-contact"><span className="hero-cta-face">{s.heroCta}</span></a></div>
      <aside className="start-price-card"><p className="kicker">{s.priceLabel}</p><p className="start-price">{s.price}</p><p>{s.priceNote}</p>
        <ul>{items.map(([name]) => <li key={name}>{hr && name === cardLabel ? "Dizajn vizitke" : name}</li>)}</ul>
        {hr && <div className="start-price-benefit"><span>Posebna pogodnost</span><strong>Mobilna aplikacija za gradilište</strong><p>Kupci Start paketa dobivaju trajnu povlaštenu cijenu.</p><a className="start-price-benefit-link" href="#start-mobile">Saznajte više o aplikaciji</a></div>}
      </aside>
    </div></section>
    <section className="start-included"><div className="shell"><div className="section-intro"><p className="kicker">{s.priceLabel}</p><h2>{s.includedLabel}</h2></div><div className="start-item-grid">{items.map(([name, copy], index) => <article className="start-item" key={name}><span className="start-item-number">0{index + 1}</span><h3>{hr && name === cardLabel ? "Dizajn vizitke" : name}</h3><p>{copy}</p></article>)}</div>{!hr && <p className="start-email-note">{s.emailNote}</p>}</div></section>
    {hr ? <StartMobileCroatian /> : <section className="start-mobile"><div className="shell start-mobile-layout"><div className="start-mobile-copy"><p className="kicker">{s.mobileEyebrow}</p><h2>{s.mobileTitle}</h2><p>{s.mobileCopy}</p><p className="start-mobile-note">{s.mobileNote}</p></div><div className="start-mobile-price"><span>Monthly subscription</span><strong>€10</strong><span className="start-mobile-period">per month</span></div></div></section>}
    <section id="start-contact" className="start-contact"><div className="shell contact"><div className="contact-panel"><div className="start-contact-copy"><div><p className="kicker">{s.ctaEyebrow}</p><h2>{s.ctaTitle}</h2></div><div className="start-direct-contact">
      <a href="mailto:hello@nosastra.co"><span className="start-contact-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2" /><path d="m4 7 8 6 8-6" /></svg></span><span><small>E-mail</small><strong>hello@nosastra.co</strong></span></a>
      <a href="tel:+385992142439"><span className="start-contact-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M6.7 3.5h3l1.4 4.2-2 1.7a15.3 15.3 0 0 0 5.5 5.5l1.7-2 4.2 1.4v3a2.5 2.5 0 0 1-2.8 2.5A17.5 17.5 0 0 1 4.2 6.3 2.5 2.5 0 0 1 6.7 3.5Z" /></svg></span><span><small>Telefon</small><strong>+385 99 214 2439</strong></span></a>
    </div></div><StartPackageForm t={t} hr={hr} /></div></div></section>
  </main>;
}
function Home({ t, hr }) { return <main id="top"><section className="hero"><div className="hero-content"><div><p className="kicker">{t.hero[0]}</p><h1>{t.hero[1]}</h1><p className="hero-copy">{t.hero[2]}</p><div className="hero-actions"><a className="hero-cta" href="#contact"><span className="hero-cta-face">{t.hero[3]}</span></a><a className="hero-secondary" href="#work">{t.hero[4]}</a></div><p className="hero-note">{t.hero[5]}</p></div></div><div className="hero-image"><picture><source media="(max-width: 800px)" srcSet="/nos-astra-hero-mobile-v1.webp" type="image/webp" /><source srcSet="/nos-astra-hero-desktop-v5.webp" type="image/webp" /><img src="/nos-astra-hero-desktop-v5.png" width="1672" height="941" fetchPriority="high" alt={hr ? "Apstraktna zvjezdana skulptura u maslinastim i grafitnim tonovima" : "Abstract olive and graphite star sculpture"} /></picture></div></section><Proof t={t} /><section id="work" className="work-section"><div className="shell"><div className="section-intro"><p className="kicker">{t.home[0]}</p><h2>{t.home[1]}</h2></div><div className="project-grid">{t.work.map((project) => <ProjectCard key={project[1]} project={project} t={t} hr={hr} />)}</div><a className="section-link" href={localPath("/work", hr)}>{t.home[2]}</a></div></section><section className="services-preview"><div className="shell"><div className="section-intro"><p className="kicker">{t.home[3]}</p><h2>{t.home[4]}</h2></div><div className="service-grid">{t.services.map((service) => <ServiceCard key={service[0]} service={service} t={t} hr={hr} />)}</div><a className="section-link" href={localPath("/services", hr)}>{t.home[5]}</a></div></section><section className="process-section"><div className="shell"><div className="section-intro"><p className="kicker">{t.home[6]}</p><h2>{t.home[7]}</h2></div><div className="steps">{t.steps.map(([number, title, copy]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section><Founder t={t} hr={hr} /><FinalCta t={t} hr={hr} /></main>; }
function PageHero({ title, copy }) { return <section className="page-hero"><div className="shell"><p className="kicker">Nos Astra</p><h1>{title}</h1><p>{copy}</p></div></section>; }
function WorkPage({ t, hr }) { return <main><PageHero title={t.pages.work[0]} copy={t.pages.work[1]} /><section className="work-section page-section"><div className="shell"><div className="project-grid project-grid-page">{t.work.map((project) => <ProjectCard key={project[1]} project={project} t={t} hr={hr} large />)}</div></div></section><FinalCta t={t} hr={hr} /></main>; }
function ServicesPage({ t, hr }) { return <main><PageHero title={t.pages.services[0]} copy={t.pages.services[1]} /><section className="page-section"><div className="shell service-list">{t.services.map((service) => <ServiceCard key={service[0]} service={service} t={t} hr={hr} full />)}</div></section><section className="unusual-cta"><div className="shell"><p className="kicker">{t.unusual[0]}</p><h2>{t.unusual[1]}</h2><p>{t.unusual[2]}</p><a className="hero-cta" href={`${localPath("/", hr)}#contact`}><span className="hero-cta-face">{t.unusual[3]}</span></a></div></section></main>; }
function AboutPage({ t, hr }) { return <main><PageHero title={t.pages.about[0]} copy={t.pages.about[1]} /><section className="about-studio"><div className="shell narrow-copy"><h2>{t.studio[0]}</h2><p>{t.studio[1]}</p><p>{t.studio[2]}</p></div></section><Founder t={t} hr={hr} /><section className="why-section"><div className="shell narrow-copy"><p className="kicker">{t.studio[3]}</p><h2>{t.studio[4]}</h2><p>{t.studio[5]}</p></div></section><FinalCta t={t} hr={hr} /></main>; }
function Footer({ t, hr }) { return <footer className="site-footer"><div className="shell"><div className="footer-main"><div className="footer-brand"><a className="brand" href={localPath("/", hr)} aria-label="Nos Astra home"><Brand /></a><p className="footer-tagline">Software &amp; AI Studio</p></div><nav className="footer-nav" aria-label={hr ? "Navigacija u podnožju" : "Footer navigation"}><a href={localPath("/work", hr)}>{t.nav[0]}</a><a href={localPath("/services", hr)}>{t.nav[1]}</a><a href={localPath("/about", hr)}>{t.nav[2]}</a><a href={`${localPath("/", hr)}#contact`}>{t.nav[3]}</a></nav><div className="footer-legal"><p>© {new Date().getFullYear()} Nos Astra.</p><div className="footer-legal-links"><a href={hr ? "/hr/privacy.html" : "/privacy.html"}>{t.footer[4]}</a></div></div></div></div></footer>; }
function App() { const rawPath = window.location.pathname.replace(/\/$/, "") || "/"; const isStartPage = rawPath === "/start"; const hr = isStartPage || rawPath === "/hr" || rawPath.startsWith("/hr/"); const path = (hr && !isStartPage ? rawPath.replace(/^\/hr/, "") : rawPath) || "/"; const t = content[hr ? "hr" : "en"]; useEffect(() => { const url = `https://www.nosastra.co${localPath(path, hr)}`; document.documentElement.lang = hr ? "hr" : "en"; document.documentElement.dir = "ltr"; const titles = { "/work": t.pages.work[0], "/services": t.pages.services[0], "/about": t.pages.about[0], "/start": t.start.priceLabel }; document.title = path === "/" ? t.title : `${titles[path] || t.pages.about[0]} — Nos Astra`; document.querySelector('meta[name="description"]')?.setAttribute("content", path === "/start" ? t.start.intro : t.description); document.querySelector('meta[property="og:locale"]')?.setAttribute("content", hr ? "hr_HR" : "en_GB"); document.querySelector('link[rel="canonical"]')?.setAttribute("href", url); document.querySelector('meta[property="og:url"]')?.setAttribute("content", url); }, [hr, path, t]); useEffect(() => { const header = document.querySelector("#root .site-header"); const onScroll = () => header?.classList.toggle("is-scrolled", window.scrollY > 24); addEventListener("scroll", onScroll, { passive: true }); onScroll(); return () => removeEventListener("scroll", onScroll); }, []); const Page = path === "/work" ? WorkPage : path === "/services" ? ServicesPage : path === "/about" ? AboutPage : path === "/start" ? StartPackagePage : Home; return <><Header t={t} hr={hr} path={path} /><Page t={t} hr={hr} /><Footer t={t} hr={hr} /><Analytics /><SpeedInsights /></>; }
if (window.location.pathname.replace(/\/$/, "") === "/hr/start") {
  window.location.replace(`/start${window.location.search}${window.location.hash}`);
} else {
  createRoot(document.getElementById("root")).render(<App />);
}
