import React from "react";

const copy = {
  en: {
    eyebrow: "SIGNAL BY NOS ASTRA", title: "Be the business", titleAccent: "AI recommends", intro: "Understand where your business stands, see which competitors AI recommends, and get practical guidance.", cta: "Create an account", see: "Explore the preview ↓", preview: "Product preview", demo: "Illustrative demo data — not live measurements", overview: "AI visibility", overviewSub: "How often your business appears in sampled answers", score: "Visibility score", scoreNote: "of sampled answers mention your business", mentions: "Brand mentions", citations: "Website citations", checks: "Sample checks", trend: "Visibility by week", trendNote: "Mention rate across your tracked questions", platforms: "By AI platform", crawler: "AI crawlers & referrals", crawlerSub: "A separate view of identified site requests and visits", requests: "AI crawler requests", referrals: "AI referral visits", pages: "Pages requested", source: "Source", activity: "Recent site activity", activityNote: "Illustrative requests from identified agents", path: "Page", agent: "Identified agent", count: "Requests", priceEyebrow: "PRICING", priceTitle: "Simple pricing for a small business.", priceIntro: "Choose the level of tracking that suits your business.", period: "/ month", starter: "Starter", growth: "Growth", starterCopy: "For one business getting a regular view of its AI presence.", growthCopy: "For a broader set of questions and platforms.", starterItems: ["10 tracked questions", "2 AI platforms", "Weekly answer checks"], growthItems: ["25 tracked questions", "3 AI platforms", "Weekly answer checks"], pricingNote: "AI crawler and referral data depends on connecting a supported site log source. Contact us to discuss setup and plan details.", priceCta: "Create an account", end: "Get a clearer picture of your AI visibility.", endCopy: "Tell us about your site and we’ll show you what Signal can help you track."
  },
  hr: {
    eyebrow: "SIGNAL BY NOS ASTRA", title: "Budite tvrtka", titleAccent: "koju AI preporučuje", intro: "Saznajte gdje se Vaša tvrtka nalazi, koje konkurente AI preporučuje i što možete poboljšati uz praktične smjernice.", cta: "Izradite račun", see: "Pogledajte prikaz ↓", preview: "Prikaz proizvoda", demo: "Primjer podataka — nisu stvarna mjerenja", overview: "AI vidljivost", overviewSub: "Koliko se često Vaše poslovanje pojavljuje u uzorku odgovora", score: "Rezultat vidljivosti", scoreNote: "odgovora u uzorku spominje Vaše poslovanje", mentions: "Spominjanja brenda", citations: "Citati web-stranice", checks: "Provjere u uzorku", trend: "Vidljivost po tjednima", trendNote: "Udio spominjanja za pitanja koja pratite", platforms: "Po AI platformi", crawler: "AI pretraživači i preporuke", crawlerSub: "Odvojen pregled prepoznatih zahtjeva i posjeta web-stranici", requests: "Zahtjevi AI pretraživača", referrals: "Posjeti iz AI izvora", pages: "Zatražene stranice", source: "Izvor", activity: "Nedavna aktivnost", activityNote: "Primjer zahtjeva prepoznatih agenata", path: "Stranica", agent: "Prepoznati agent", count: "Zahtjevi", priceEyebrow: "CIJENE", priceTitle: "Jednostavne cijene za male tvrtke.", priceIntro: "Odaberite opseg praćenja koji odgovara Vašem poslovanju.", period: "/ mjesečno", starter: "Starter", growth: "Growth", starterCopy: "Za redovit pregled AI prisutnosti jedne tvrtke.", growthCopy: "Za širi skup pitanja i platformi.", starterItems: ["10 pitanja za praćenje", "2 AI platforme", "Tjedne provjere odgovora"], growthItems: ["25 pitanja za praćenje", "3 AI platforme", "Tjedne provjere odgovora"], pricingNote: "Podaci o AI pretraživačima i posjetima ovise o povezivanju podržanog izvora zapisa web-stranice. Javite nam se kako bismo dogovorili postavljanje i detalje paketa.", priceCta: "Izradite račun", end: "Steknite jasniju sliku o svojoj AI vidljivosti.", endCopy: "Recite nam nešto o svojoj stranici i pokazat ćemo Vam što Signal može pratiti."
  }
};

const capabilityStory = {
  en: {
    eyebrow: "THE QUESTIONS SIGNAL HELPS YOU ANSWER",
    title: "From being seen to being chosen.",
    lead: "When someone asks AI to recommend a business like yours, the answer can shape their shortlist before they ever reach your website. Signal is being built to help you understand that journey and decide where to focus next.",
    pillars: [
      ["Visibility", "Do you appear when buyers ask?", "A single AI answer is only a snapshot. Signal looks at a defined set of questions your customers might ask and shows when your business appears, when competitors appear instead, and how that changes across platforms and over time.", "See which buying questions include your business and which leave it out."],
      ["Traffic", "Does that attention reach your website?", "AI tools can access your pages without sending a customer to your website. Signal separates that background activity from visits that come through from AI tools. With a supported website connection, you can see which pages receive attention and whether that attention is becoming visits.", "See whether AI exposure is also bringing people to you."],
      ["Citations", "Which pages earn attention—and visits?", "Signal shows which of your pages AI tools cite in the answers it checks. A citation gives someone a path to your website; connected AI referral data shows which pages visitors actually land on. Looking at both helps you spot pages that are cited often, pages that receive visits from AI tools, and gaps between the two.", "Focus on the pages bringing visitors and improve the ones with untapped potential."],
      ["Recommendations", "Why did AI choose a competitor?", "When a competitor appears for a question that matters to your business, Signal will look into the reason, not just count the mention. It will review the answer and any cited competitor pages, compare what they explain with what customers can find on your site, and show what may be missing. That could be clearer pricing, a defined service area, proof of past work, or a better explanation of a service. Each suggestion will point back to the question and evidence behind it.", "Know what the competitor is getting credit for and what to improve on your own site."],
    ],
    howEyebrow: "HOW IT WORKS",
    howTitle: "Your website is already live. Signal connects the dots.",
    howSteps: [
      ["Add your domain", "Tell Signal which existing website belongs to your business and where it is hosted. Choose Vercel, Cloudflare, or AWS during setup; your website stays where it is."],
      ["Connect your website logs", "At launch, connect your website logs from Vercel, Cloudflare, or AWS. Signal brings AI crawler requests and visits referred by AI tools into one clear view."],
      ["See the activity that matters", "Explore which pages AI crawlers request and which pages people reach from AI tools. You can see whether AI attention is becoming visits, and which parts of your site those visitors actually reach."],
      ["Find the gaps. Improve your chances.", "Planned answer checks will compare the same buyer questions across AI platforms. If ChatGPT mentions you but Gemini does not, or a competitor appears instead, Signal will examine the observed answers, cited pages, and the competitor's website alongside yours. It will point to likely gaps and suggest specific improvements backed by that evidence. Claude checks are planned as the platform coverage expands."],
    ],
  },
  hr: {
    eyebrow: "PITANJA NA KOJA VAM SIGNAL POMAŽE ODGOVORITI",
    title: "Od vidljivosti do preporuke.",
    lead: "Kad netko pita AI da preporuči tvrtku poput Vaše, odgovor može utjecati na izbor prije nego što osoba uopće posjeti Vašu web-stranicu. Signal razvijamo kako biste razumjeli taj put i lakše odlučili što dalje poboljšati.",
    pillars: [
      ["Vidljivost", "Pojavljujete li se kad kupci pitaju?", "Jedan AI odgovor samo je trenutačni prikaz. Signal promatra određeni skup pitanja koja bi Vaši kupci mogli postaviti te pokazuje kada se pojavljuje Vaša tvrtka, kada se umjesto nje pojavljuju konkurenti i kako se to mijenja kroz vrijeme i među platformama.", "Otkrijte za koja se pitanja Vaša tvrtka spominje, a za koja izostaje."],
      ["Promet", "Dolaze li ljudi nakon toga na Vašu stranicu?", "AI alati mogu pristupiti Vašim stranicama, a da Vam ne pošalju nijednog posjetitelja. Signal odvaja tu pozadinsku aktivnost od posjeta koji dolaze iz AI alata. Uz podržanu vezu s web-stranicom možete vidjeti koje stranice privlače pozornost i pretvara li se ona u posjete.", "Saznajte dovodi li Vam AI prisutnost i ljude na stranicu."],
      ["Citati", "Koje stranice privlače pozornost i posjete?", "Signal pokazuje koje se Vaše stranice citiraju u AI odgovorima koje provjerava. Citat nekome otvara put do Vaše web-stranice, a povezani podaci o posjetima iz AI alata pokazuju na koje stranice posjetitelji doista dolaze. Usporedbom tih podataka vidite koje se stranice često citiraju, koje primaju posjete iz AI alata i gdje između toga postoji razlika.", "Usmjerite trud na stranice koje dovode posjetitelje i poboljšajte one s neiskorištenim potencijalom."],
      ["Preporuke", "Zašto je AI preporučio konkurenta?", "Kad se konkurent pojavi u odgovoru na pitanje važno za Vaše poslovanje, Signal će istražiti zašto, a ne samo zabilježiti spominjanje. Pregledat će odgovor i eventualne citirane stranice konkurenta, usporediti što one objašnjavaju s informacijama na Vašoj stranici i pokazati što možda nedostaje. To mogu biti jasnije cijene, područje rada, primjeri prethodnih projekata ili bolji opis usluge. Svaki prijedlog bit će povezan s pitanjem i opažanjima na kojima se temelji.", "Saznajte zbog čega se ističe konkurent i što konkretno možete poboljšati."],
    ],
    howEyebrow: "KAKO SIGNAL RADI",
    howTitle: "Vaša je stranica već aktivna. Signal povezuje podatke.",
    howSteps: [
      ["Dodajte svoju domenu", "Recite Signalu koja postojeća web-stranica pripada Vašoj tvrtki i gdje je smještena. Pri postavljanju odaberite Vercel, Cloudflare ili AWS; Vaša stranica ostaje ondje gdje jest."],
      ["Povežite zapise stranice", "Pri pokretanju povežite zapise svoje web-stranice na platformi Vercel, Cloudflare ili AWS. Signal će na jednom mjestu prikazati zahtjeve AI pretraživača i posjete koji dolaze iz AI alata."],
      ["Pogledajte što je važno", "Otkrijte koje stranice traže AI pretraživači i na koje stranice ljudi dolaze iz AI alata. Vidjet ćete pretvara li se pozornost AI alata u posjete i na koje dijelove Vaše stranice ti posjetitelji doista dolaze."],
      ["Pronađite razlike. Poboljšajte svoje izglede.", "Planirane provjere odgovora uspoređivat će ista pitanja kupaca među AI platformama. Ako Vas ChatGPT spominje, a Gemini ne, ili se umjesto Vas pojavi konkurent, Signal će pregledati opažene odgovore, citirane stranice i konkurentsku web-stranicu usporedno s Vašom. Pokazat će moguće nedostatke i predložiti konkretna poboljšanja utemeljena na tim opažanjima. Provjere na Claudeu planirane su kako se bude širila podrška za platforme."],
    ],
  },
};

function BeaconMark() {
  return <svg viewBox="0 0 64 64" fill="none" aria-hidden="true" focusable="false"><circle cx="16" cy="32" r="5" fill="currentColor" /><path d="M25 22c10 5 10 15 0 20M31 12c17 10 17 30 0 40M38 5c21 13 21 41 0 54" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round" /></svg>;
}
function MiniBars() {
  return <div className="signal-bars" aria-hidden="true">{[35, 45, 42, 58, 54, 67, 72, 68].map((height, index) => <div key={index}><span style={{ height: `${height}%` }} /></div>)}</div>;
}

function DashboardFrame({ label, title, subtitle, children }) {
  return <div className="signal-dashboard" aria-label={label}><div className="signal-dashboard-rail"><span className="signal-dashboard-logo"><BeaconMark /></span><span className="signal-rail-line" /><span className="signal-rail-line short" /><span className="signal-rail-line" /></div><div className="signal-dashboard-main"><div className="signal-dashboard-top"><strong>signal<span>.</span></strong><span>DEMO WORKSPACE</span></div><div className="signal-dashboard-heading"><div><span className="signal-dash-overline">OVERVIEW / DEMO COMPANY</span><h3>{title}</h3><p>{subtitle}</p></div><span className="signal-sample-pill">SAMPLE DATA</span></div>{children}</div></div>;
}

export default function SignalPage({ hr }) {
  const s = copy[hr ? "hr" : "en"];
  const story = capabilityStory[hr ? "hr" : "en"];
  const localPreview = ["localhost", "127.0.0.1"].includes(window.location.hostname);
  const appUrl = (import.meta.env.VITE_SIGNAL_APP_URL || (localPreview ? `${window.location.protocol}//${window.location.hostname}:3105` : "https://signal-by-nosastra.vercel.app")).replace(/\/$/, "");
  const signUpUrl = `${appUrl}/auth/sign-up`;
  return <>
    <header className="signal-site-header"><div className="shell signal-nav"><a className="signal-wordmark" href={hr ? "/hr" : "/"} aria-label="Signal by Nos Astra"><span className="signal-wordmark-mark"><BeaconMark /></span><span><span>signal<span className="signal-wordmark-dot">.</span></span><small>BY NOS ASTRA</small></span></a><nav aria-label={hr ? "Glavna navigacija" : "Main navigation"}><a href="#signal-preview">{hr ? "Pregled" : "Product"}</a><a href="#signal-tracks">{hr ? "Mogućnosti" : "Features"}</a><a href="#signal-pricing">{hr ? "Cijene" : "Pricing"}</a><a className="signal-nav-locale" href={hr ? "/signal" : "/hr/signal"}>{hr ? "EN" : "HR"}</a></nav></div></header>
    <main className="signal-page">
    <section className="signal-hero"><div className="shell signal-hero-inner"><div className="signal-hero-copy"><p className="kicker"><span className="signal-live-dot" />{hr ? "VAŠA AI PRISUTNOST, JASNO PRIKAZANA" : "YOUR AI PRESENCE, MADE VISIBLE"}</p><h1>{s.title}<br /><em>{s.titleAccent}</em></h1><p>{s.intro}</p><div className="signal-actions"><a className="signal-primary-cta" href={signUpUrl}>{s.cta}<span aria-hidden="true">↗</span></a></div></div><div className="signal-hero-visual signal-hero-capabilities"><div className="signal-hero-art signal-hero-image"><img src="/signal-hero-capabilities-v5.png" width="1536" height="1024" fetchPriority="high" alt={hr ? "AI vidljivost, citati, promet i preporuke" : "Visibility, citations, traffic and recommendations"} /><span className="signal-image-glow" /></div></div></div></section>
    <section id="signal-tracks" className="signal-capabilities"><div className="shell"><div className="signal-capabilities-intro"><p className="kicker">{story.eyebrow}</p><h2>{story.title}</h2><p>{story.lead}</p></div><div className="signal-pillar-list">{story.pillars.map(([name, question, explanation, outcome], index) => <article className="signal-pillar" key={name}><div className="signal-pillar-label"><span>0{index + 1} / 04</span><h3>{name}</h3></div><div className="signal-pillar-content"><h4>{question}</h4><p>{explanation}</p><p className="signal-pillar-outcome"><span aria-hidden="true">↗</span>{outcome}</p></div></article>)}</div></div></section>
    <section id="signal-how" className="signal-how"><div className="shell"><div className="signal-how-heading"><p className="kicker">{story.howEyebrow}</p><h2>{story.howTitle}</h2></div><ol className="signal-how-steps">{story.howSteps.map(([title, description], index) => <li key={title} className="signal-how-step"><div className="signal-how-art"><img src={["/signal-how-domain-v1.png", "/signal-how-logs-v1.png", "/signal-how-insights-v1.png", "/signal-how-compare-v1.png"][index]} width="1792" height="1024" loading="lazy" alt="" /></div><div className="signal-how-copy"><span className="signal-how-index">0{index + 1} / 0{story.howSteps.length}</span><h3>{title}</h3><p>{description}</p></div></li>)}</ol></div></section>
    <section id="signal-preview" className="signal-preview"><div className="shell"><div className="signal-section-heading"><div><p className="kicker">{s.preview}</p><h2>{hr ? "Dva pogleda. Jedna jasnija slika." : "Two views. One clearer picture."}</h2></div></div><div className="signal-preview-stack">
      <div className="signal-preview-item"><div className="signal-preview-caption"><span>01 / {s.overview}</span><p>{s.overviewSub}</p></div><DashboardFrame label={s.overview} title={s.overview} subtitle={s.overviewSub}><div className="signal-metrics"><div className="signal-metric featured"><small>{s.score}</small><strong>42<span>%</span></strong><em>{s.scoreNote}</em></div><div className="signal-metric"><small>{s.mentions}</small><strong>34</strong><em>+6 {hr ? "prema prošlom uzorku" : "vs previous sample"}</em></div><div className="signal-metric"><small>{s.citations}</small><strong>18</strong><em>{hr ? "u uzorku odgovora" : "in sampled answers"}</em></div><div className="signal-metric"><small>{s.checks}</small><strong>80</strong><em>{hr ? "u četiri tjedna" : "over four weeks"}</em></div></div><div className="signal-dash-bottom"><div className="signal-panel"><div className="signal-panel-title"><strong>{s.trend}</strong><small>{s.trendNote}</small></div><MiniBars /><div className="signal-chart-labels"><span>W1</span><span>W2</span><span>W3</span><span>W4</span></div></div><div className="signal-panel"><div className="signal-panel-title"><strong>{s.platforms}</strong><small>{hr ? "Udio spominjanja u uzorku" : "Sampled mention rate"}</small></div>{[["ChatGPT", "48%", 48], ["Gemini", "36%", 36]].map(([name, value, width]) => <div className="signal-platform" key={name}><div><span>{name}</span><strong>{value}</strong></div><i><b style={{ width: `${width}%` }} /></i></div>)}</div></div></DashboardFrame></div>
      <div className="signal-preview-item"><div className="signal-preview-caption"><span>02 / {s.crawler}</span><p>{s.crawlerSub}</p></div><DashboardFrame label={s.crawler} title={s.crawler} subtitle={s.crawlerSub}><div className="signal-metrics signal-metrics-three"><div className="signal-metric featured"><small>{s.requests}</small><strong>126</strong><em>{hr ? "zadnjih 7 dana" : "last 7 days"}</em></div><div className="signal-metric"><small>{s.referrals}</small><strong>14</strong><em>{hr ? "prepoznati izvori" : "identified sources"}</em></div><div className="signal-metric"><small>{s.pages}</small><strong>9</strong><em>{hr ? "jedinstvenih putanja" : "distinct paths"}</em></div></div><div className="signal-panel signal-activity"><div className="signal-panel-title"><strong>{s.activity}</strong><small>{s.activityNote}</small></div><div className="signal-table"><div className="signal-table-row signal-table-head"><span>{s.path}</span><span>{s.agent}</span><span>{s.count}</span></div>{[["/services", "GPTBot", "38"], ["/about", "ClaudeBot", "21"], ["/pricing", "PerplexityBot", "16"]].map(([path, agent, count]) => <div className="signal-table-row" key={path}><span>{path}</span><span>{agent}</span><strong>{count}</strong></div>)}</div></div></DashboardFrame></div>
    </div></div></section>
    <section id="signal-pricing" className="signal-pricing"><div className="shell"><div className="signal-section-heading"><div><p className="kicker">{s.priceEyebrow}</p><h2>{s.priceTitle}</h2></div></div><div className="signal-pricing-grid">{[[s.starter, "€9", s.starterCopy, s.starterItems], [s.growth, "€19", s.growthCopy, s.growthItems]].map(([name, price, description, items]) => <article className="signal-plan" key={name}><div><span className="signal-plan-name">{name}</span><p>{description}</p></div><div className="signal-plan-price"><strong>{price}</strong><span>{s.period}</span></div><ul>{items.map(item => <li key={item}>{item}</li>)}</ul><a href={signUpUrl}>{s.priceCta} <span aria-hidden="true">↗</span></a></article>)}</div><p className="signal-pricing-note">{s.pricingNote}</p></div></section>
    <section className="signal-end"><div className="shell"><div><p className="kicker">SIGNAL / BY NOS ASTRA</p><h2>{s.end}</h2><p>{s.endCopy}</p></div><a className="signal-primary-cta" href={signUpUrl}>{s.cta}<span aria-hidden="true">↗</span></a></div></section>
  </main>
  </>;
}
