import React from "react";

const copy = {
  en: {
    eyebrow: "SIGNAL BY NOS ASTRA", title: "Be the business", titleAccent: "AI recommends", intro: "Understand where your business stands, see which competitors AI recommends, and get practical guidance.", cta: "Create an account", see: "Explore the preview ↓", preview: "Product preview", demo: "Illustrative demo data — not live measurements", overview: "AI visibility", overviewSub: "How often your business appears in sampled answers", score: "Visibility score", scoreNote: "of sampled answers mention your business", mentions: "Brand mentions", citations: "Website citations", checks: "Sample checks", trend: "Visibility by week", trendNote: "Mention rate across your tracked questions", platforms: "By AI platform", crawler: "AI crawlers & referrals", crawlerSub: "A separate view of identified site requests and visits", requests: "AI crawler requests", referrals: "AI referral visits", pages: "Pages requested", source: "Source", activity: "Recent site activity", activityNote: "Illustrative requests from identified agents", path: "Page", agent: "Identified agent", count: "Requests", tracksEyebrow: "WHAT SIGNAL TRACKS", tracksTitle: "A small set of useful signals.", tracks: [["Answer visibility", "Track whether your business is mentioned or cited in a defined set of AI answers."], ["Site access", "See requests from identified AI crawlers and visits with known AI referrers, when source data is available."], ["Changes over time", "Compare weekly samples and spot meaningful changes in mentions, citations and competing names."]], caveat: "Sampled answers are not a universal AI ranking. A crawler request does not mean your page was used in an answer.", priceEyebrow: "PRICING", priceTitle: "Simple pricing for a small business.", priceIntro: "Choose the level of tracking that suits your business.", period: "/ month", starter: "Starter", growth: "Growth", starterCopy: "For one business getting a regular view of its AI presence.", growthCopy: "For a broader set of questions and platforms.", starterItems: ["10 tracked questions", "2 AI platforms", "Weekly answer checks"], growthItems: ["25 tracked questions", "3 AI platforms", "Weekly answer checks"], pricingNote: "AI crawler and referral data depends on connecting a supported site log source. Contact us to discuss setup and plan details.", priceCta: "Create an account", end: "Get a clearer picture of your AI visibility.", endCopy: "Tell us about your site and we’ll show you what Signal can help you track."
  },
  hr: {
    eyebrow: "SIGNAL BY NOS ASTRA", title: "Budite tvrtka", titleAccent: "koju AI preporučuje", intro: "Saznajte gdje se Vaša tvrtka nalazi, koje konkurente AI preporučuje i što možete poboljšati uz praktične smjernice.", cta: "Izradite račun", see: "Pogledajte prikaz ↓", preview: "Prikaz proizvoda", demo: "Primjer podataka — nisu stvarna mjerenja", overview: "AI vidljivost", overviewSub: "Koliko se često Vaše poslovanje pojavljuje u uzorku odgovora", score: "Rezultat vidljivosti", scoreNote: "odgovora u uzorku spominje Vaše poslovanje", mentions: "Spominjanja brenda", citations: "Citati web-stranice", checks: "Provjere u uzorku", trend: "Vidljivost po tjednima", trendNote: "Udio spominjanja za pitanja koja pratite", platforms: "Po AI platformi", crawler: "AI pretraživači i preporuke", crawlerSub: "Odvojen pregled prepoznatih zahtjeva i posjeta web-stranici", requests: "Zahtjevi AI pretraživača", referrals: "Posjeti iz AI izvora", pages: "Zatražene stranice", source: "Izvor", activity: "Nedavna aktivnost", activityNote: "Primjer zahtjeva prepoznatih agenata", path: "Stranica", agent: "Prepoznati agent", count: "Zahtjevi", tracksEyebrow: "ŠTO SIGNAL PRATI", tracksTitle: "Nekoliko korisnih pokazatelja.", tracks: [["Vidljivost u odgovorima", "Pratite spominje li se ili citira Vaše poslovanje u zadanom uzorku AI odgovora."], ["Pristup stranici", "Pogledajte zahtjeve prepoznatih AI pretraživača i posjete iz poznatih AI izvora, kada su podaci dostupni."], ["Promjene kroz vrijeme", "Usporedite tjedne uzorke i uočite važne promjene u spominjanjima, citatima i konkurentskim nazivima."]], caveat: "Uzorak odgovora nije univerzalna AI ljestvica. Zahtjev pretraživača ne znači da je stranica korištena u odgovoru.", priceEyebrow: "CIJENE", priceTitle: "Jednostavne cijene za male tvrtke.", priceIntro: "Odaberite opseg praćenja koji odgovara Vašem poslovanju.", period: "/ mjesečno", starter: "Starter", growth: "Growth", starterCopy: "Za redovit pregled AI prisutnosti jedne tvrtke.", growthCopy: "Za širi skup pitanja i platformi.", starterItems: ["10 pitanja za praćenje", "2 AI platforme", "Tjedne provjere odgovora"], growthItems: ["25 pitanja za praćenje", "3 AI platforme", "Tjedne provjere odgovora"], pricingNote: "Podaci o AI pretraživačima i posjetima ovise o povezivanju podržanog izvora zapisa web-stranice. Javite nam se kako bismo dogovorili postavljanje i detalje paketa.", priceCta: "Izradite račun", end: "Steknite jasniju sliku o svojoj AI vidljivosti.", endCopy: "Recite nam nešto o svojoj stranici i pokazat ćemo Vam što Signal može pratiti."
  }
};

function BeaconMark() {
  return <svg viewBox="0 0 64 64" fill="none" aria-hidden="true" focusable="false"><circle cx="16" cy="32" r="5" fill="currentColor" /><path d="M25 22c10 5 10 15 0 20M31 12c17 10 17 30 0 40M38 5c21 13 21 41 0 54" stroke="currentColor" strokeWidth="4.5" strokeLinecap="round" /></svg>;
}
function MiniBars() {
  return <div className="signal-bars" aria-hidden="true">{[35, 45, 42, 58, 54, 67, 72, 68].map((height, index) => <div key={index}><span style={{ height: `${height}%` }} /></div>)}</div>;
}

function DashboardFrame({ label, title, subtitle, children }) {
  return <div className="signal-dashboard" aria-label={label}><div className="signal-dashboard-rail"><span className="signal-dashboard-logo"><BeaconMark /></span><span className="signal-rail-line" /><span className="signal-rail-line short" /><span className="signal-rail-line" /></div><div className="signal-dashboard-main"><div className="signal-dashboard-top"><strong>signal<span>.</span></strong><span>DEMO WORKSPACE</span></div><div className="signal-dashboard-heading"><div><span className="signal-dash-overline">OVERVIEW / DEMO COMPANY</span><h3>{title}</h3><p>{subtitle}</p></div><span className="signal-sample-pill">SAMPLE DATA</span></div>{children}</div></div>;
}

export default function SignalPage({ hr }) {
  const s = copy[hr ? "hr" : "en"];
  const localPreview = ["localhost", "127.0.0.1"].includes(window.location.hostname);
  const appUrl = (import.meta.env.VITE_SIGNAL_APP_URL || (localPreview ? `${window.location.protocol}//${window.location.hostname}:3105` : "")).replace(/\/$/, "");
  const signUpUrl = `${appUrl}/auth/sign-up`;
  return <>
    <header className="signal-site-header"><div className="shell signal-nav"><a className="signal-wordmark" href={hr ? "/hr" : "/"} aria-label="Signal by Nos Astra"><span className="signal-wordmark-mark"><BeaconMark /></span><span><span>signal<span className="signal-wordmark-dot">.</span></span><small>BY NOS ASTRA</small></span></a><nav aria-label={hr ? "Glavna navigacija" : "Main navigation"}><a href="#signal-preview">{hr ? "Pregled" : "Product"}</a><a href="#signal-tracks">{hr ? "Mogućnosti" : "Features"}</a><a href="#signal-pricing">{hr ? "Cijene" : "Pricing"}</a><a className="signal-nav-locale" href={hr ? "/signal" : "/hr/signal"}>{hr ? "EN" : "HR"}</a></nav></div></header>
    <main className="signal-page">
    <section className="signal-hero"><div className="shell signal-hero-inner"><div className="signal-hero-copy"><p className="kicker"><span className="signal-live-dot" />{hr ? "VAŠA AI PRISUTNOST, JASNO PRIKAZANA" : "YOUR AI PRESENCE, MADE VISIBLE"}</p><h1>{s.title}<br /><em>{s.titleAccent}</em></h1><p>{s.intro}</p><div className="signal-actions"><a className="signal-primary-cta" href={signUpUrl}>{s.cta}<span aria-hidden="true">↗</span></a></div></div><div className="signal-hero-visual signal-hero-capabilities"><div className="signal-hero-art signal-hero-image"><img src="/signal-hero-capabilities-v5.png" width="1536" height="1024" fetchPriority="high" alt={hr ? "AI vidljivost, citati, promet i preporuke" : "Visibility, citations, traffic and recommendations"} /><span className="signal-image-glow" /></div></div></div></section>
    <section id="signal-preview" className="signal-preview"><div className="shell"><div className="signal-section-heading"><div><p className="kicker">{s.preview}</p><h2>{hr ? "Dva pogleda. Jedna jasnija slika." : "Two views. One clearer picture."}</h2></div></div><div className="signal-preview-stack">
      <div className="signal-preview-item"><div className="signal-preview-caption"><span>01 / {s.overview}</span><p>{s.overviewSub}</p></div><DashboardFrame label={s.overview} title={s.overview} subtitle={s.overviewSub}><div className="signal-metrics"><div className="signal-metric featured"><small>{s.score}</small><strong>42<span>%</span></strong><em>{s.scoreNote}</em></div><div className="signal-metric"><small>{s.mentions}</small><strong>34</strong><em>+6 {hr ? "prema prošlom uzorku" : "vs previous sample"}</em></div><div className="signal-metric"><small>{s.citations}</small><strong>18</strong><em>{hr ? "u uzorku odgovora" : "in sampled answers"}</em></div><div className="signal-metric"><small>{s.checks}</small><strong>80</strong><em>{hr ? "u četiri tjedna" : "over four weeks"}</em></div></div><div className="signal-dash-bottom"><div className="signal-panel"><div className="signal-panel-title"><strong>{s.trend}</strong><small>{s.trendNote}</small></div><MiniBars /><div className="signal-chart-labels"><span>W1</span><span>W2</span><span>W3</span><span>W4</span></div></div><div className="signal-panel"><div className="signal-panel-title"><strong>{s.platforms}</strong><small>{hr ? "Udio spominjanja u uzorku" : "Sampled mention rate"}</small></div>{[["ChatGPT", "48%", 48], ["Gemini", "36%", 36]].map(([name, value, width]) => <div className="signal-platform" key={name}><div><span>{name}</span><strong>{value}</strong></div><i><b style={{ width: `${width}%` }} /></i></div>)}</div></div></DashboardFrame></div>
      <div className="signal-preview-item"><div className="signal-preview-caption"><span>02 / {s.crawler}</span><p>{s.crawlerSub}</p></div><DashboardFrame label={s.crawler} title={s.crawler} subtitle={s.crawlerSub}><div className="signal-metrics signal-metrics-three"><div className="signal-metric featured"><small>{s.requests}</small><strong>126</strong><em>{hr ? "zadnjih 7 dana" : "last 7 days"}</em></div><div className="signal-metric"><small>{s.referrals}</small><strong>14</strong><em>{hr ? "prepoznati izvori" : "identified sources"}</em></div><div className="signal-metric"><small>{s.pages}</small><strong>9</strong><em>{hr ? "jedinstvenih putanja" : "distinct paths"}</em></div></div><div className="signal-panel signal-activity"><div className="signal-panel-title"><strong>{s.activity}</strong><small>{s.activityNote}</small></div><div className="signal-table"><div className="signal-table-row signal-table-head"><span>{s.path}</span><span>{s.agent}</span><span>{s.count}</span></div>{[["/services", "GPTBot", "38"], ["/about", "ClaudeBot", "21"], ["/pricing", "PerplexityBot", "16"]].map(([path, agent, count]) => <div className="signal-table-row" key={path}><span>{path}</span><span>{agent}</span><strong>{count}</strong></div>)}</div></div></DashboardFrame></div>
    </div></div></section>
    <section id="signal-tracks" className="signal-tracks"><div className="shell"><div className="signal-section-heading"><div><p className="kicker">{s.tracksEyebrow}</p><h2>{s.tracksTitle}</h2></div></div><div className="signal-tracks-grid">{s.tracks.map(([title, description], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div><p className="signal-caveat">{s.caveat}</p></div></section>
    <section id="signal-pricing" className="signal-pricing"><div className="shell"><div className="signal-section-heading"><div><p className="kicker">{s.priceEyebrow}</p><h2>{s.priceTitle}</h2></div></div><div className="signal-pricing-grid">{[[s.starter, "€9", s.starterCopy, s.starterItems], [s.growth, "€19", s.growthCopy, s.growthItems]].map(([name, price, description, items]) => <article className="signal-plan" key={name}><div><span className="signal-plan-name">{name}</span><p>{description}</p></div><div className="signal-plan-price"><strong>{price}</strong><span>{s.period}</span></div><ul>{items.map(item => <li key={item}>{item}</li>)}</ul><a href={signUpUrl}>{s.priceCta} <span aria-hidden="true">↗</span></a></article>)}</div><p className="signal-pricing-note">{s.pricingNote}</p></div></section>
    <section className="signal-end"><div className="shell"><div><p className="kicker">SIGNAL / BY NOS ASTRA</p><h2>{s.end}</h2><p>{s.endCopy}</p></div><a className="signal-primary-cta" href={signUpUrl}>{s.cta}<span aria-hidden="true">↗</span></a></div></section>
  </main>
  </>;
}
